project:
  type: website
  output-dir: docs

execute:
  freeze: auto

website:
  title: "MScIDS Notes"
  google-analytics: "G-NZ8462CXQ1"
  search: true
  
  navbar:
    left:
      - text: "Home"
        href: index.qmd
      - text: "Datawarehouse & Data Lake"
        href: fa26/dwl/dwl_notes.qmd
      - text: "Generative AI"
        href: fa26/gen/gen_notes.qmd
    right:
      - text: "Old Notes"
        menu:
          - text: "**SP26**"
          - text: "CIP — Notes"
            href: sp26/cip/cip_notes.qmd
          - text: "DBM — Notes"
            href: sp26/dbm/dbm_notes.qmd
          - text: "DBM — Exercises"
            href: sp26/dbm/dbm_exercises.qmd
          - text: "DevOps — Notes"
            href: sp26/devops/devops_notes.qmd
          - text: "DevOps — Exercises"
            href: sp26/devops/devops_exercises.qmd
          - text: "DQ — Notes"
            href: sp26/dq/dq_notes.qmd
          - text: "DQ — Exercises"
            href: sp26/dq/dq_exercises.qmd
          - text: "MPM1 — Notes"
            href: sp26/mpm1/mpm1_notes.qmd
          - text: "MPM1 — Exercises"
            href: sp26/mpm1/mpm1_exercises.qmd
          - text: "RTP — Notes"
            href: sp26/rtp/rtp_notes.qmd
          - text: "RTP — Exercises"
            href: sp26/rtp/rtp_exercises.qmd
          - text: "RTP — Exercises (Rep.)"
            href: sp26/rtp/rtp_exercises_rep.qmd
          - text: "---"
          - text: "**FA25**"
          - text: "CSC — Notes"
            href: fa25/csc/csc_notes.qmd
          - text: "CSC — Exercises"
            href: fa25/csc/csc_exercises.qmd
          - text: "CSC — Exam Summary (PDF)"
            href: fa25/csc/csc_exam_summary.pdf
          - text: "DOE — Notes"
            href: fa25/doe/doe_notes.qmd
          - text: "DOE — Exercises"
            href: fa25/doe/doe_exercises.qmd
          - text: "DOE — Exam Summary (PDF)"
            href: fa25/doe/doe_exam_summary.pdf
          - text: "LIA1 — Notes"
            href: fa25/lia1/lia1_notes.qmd
          - text: "LIA1 — Exercises"
            href: fa25/lia1/lia1_exercises.qmd
          - text: "PDS — Notes"
            href: fa25/pds/pds_notes.qmd
          - text: "PDS — Exercises"
            href: fa25/pds/pds_exercises.qmd
          - text: "PDS — Additional Exercises"
            href: fa25/pds/pds_additional_exercises.qmd
          - text: "PDS — Mock Exam"
            href: fa25/pds/pds_mock_exam.qmd
          - text: "PDS — Modul Exam (FS23)"
            href: fa25/pds/pds_modul_exam_fs23.qmd
          - text: "R-Bootcamp — Notes"
            href: fa25/r_bootcamp/r_bootcamp_notes.qmd
          - text: "SA — Notes"
            href: fa25/sa/sa_notes.qmd
          - text: "SA — Exercises"
            href: fa25/sa/sa_exercises.qmd
      - text: "How to"
        menu:
          - text: "Terminal"
            href: howTo/terminal.qmd
          - text: "Git/GitHub"
            href: howTo/git.qmd
          - text: "Python"
            href: howTo/python.qmd
          - text: "Python Packages"
            href: howTo/pythonPackages.qmd
          - text: "Python Project"
            href: howTo/pythonProject.qmd
      - text: "Resources"
        href: resources.qmd

  page-footer:
    left: "MScIDS Notes"
    right: "Created with [Quarto](https://quarto.org/) by Nils Rechberger"

format:
  html:
    theme:
      light: cosmo
      dark: darkly
    css: styles.css
    toc: true
    toc-depth: 3
    toc-location: right
    code-copy: true
    code-fold: show
    html-math-method: katex
  pdf: default