project:
  type: website
  output-dir: docs

execute:
  freeze: auto

website:
  title: "MScIDS Notes"
  google-analytics: "G-NZ8462CXQ1"
  search: true
  
  navbar:
    left:
      - text: "Home"
        href: index.qmd
      - text: "Applied Machine Learning and Predictive Modelling 1"
        menu:
          - text: "Notes"
            href: fs26/mpm1/mpm1_notes.qmd
          - text: "Exercises"
            href: fs26/mpm1/mpm1_exercises.qmd
      - text: "Data Quality"
        menu:
          - text: "Notes"
            href: fs26/dq/dq_notes.qmd
          - text: "Exercises"
            href: fs26/dq/dq_exercises.qmd
      - text: "Discrete Response, Time Series and Panel Data"
        menu:
          - text: "Notes"
            href: fs26/rtp/rtp_notes.qmd
          - text: "Exercises"
            href: fs26/rtp/rtp_exercises.qmd
    right:
      - text: "How to"
        menu:
          - text: "Terminal"
            href: "howTo/terminal.qmd"
          - text: "Git/GitHub"
            href: "howTo/git.qmd"
          - text: "Python"
            href: "howTo/python.qmd"
          - text: "Python Packages"
            href: "howTo/pythonPackages.qmd"
          - text: "Python Project"
            href: "howTo/pythonProject.qmd"
      - text: "Resources"
        href: resources.qmd

  page-footer:
    left: "MScIDS Notes"
    right: "Created with [Quarto](https://quarto.org/) by Nils Rechberger"

format:
  html:
    theme:
      light: cosmo
      dark: darkly
    css: styles.css
    toc: true
    toc-depth: 3
    toc-location: right
    code-copy: true
    code-fold: show
    html-math-method: katex
  pdf: default