---
title: "Useful Resources"
---

# Python

* [**W3Schools**](https://www.w3schools.com/python/default.asp): A great starting point for beginners with Python basics and simple examples.
* [**Real Python**](https://realpython.com/): Comprehensive tutorials and advanced topics for a deeper dive into the language.
* [**Geeks for Geeks**](https://www.geeksforgeeks.org/): A comprehensive educational portal that empowers learners across domains.
* [**Python Cheat Sheet**](files/cheat_sheet_python.pdf): Real Python Pocket Reference for python coding.
* [**Numpy Cheat Sheet**](files/cheat_sheet_numpy.pdf): A quick reference guide covering essential functions for numerical operations.
* [**Pandas Cheat Sheet**](files/cheat_sheet_numpy.pdf): Summarizes the core commands for efficient data manipulation and analysis.
* [**Matplotlib Cheat Sheet**](files/cheat_sheet_numpy.pdf): Overview to create static, animated, and interactive visualizations.

---

# R

* [**Tidyverse Cheat Sheet**](files/cheat_sheet_tidyverse_ggplot2.pdf): A small Tidyverse for Beginners overview.
* [**ggplot2 Cheat Sheet**](files/cheat_sheet_ggplot2.pdf): Plotting with ggplot2 in R.

---

# Software Development

* [**W3Schools Git Tutorial**](https://www.w3schools.com/git/default.asp): An easy-to-follow introduction to the fundamentals of version control with Git.
* [**Linux Cheat Sheet**](files/cheat_sheet_linux.pdf): Overview of the most common Linux terminal commands, written by Maths et al.

---

# Data Science

* [**Towards Data Science**](https://towardsdatascience.com/): Collection of articles, tutorials, and guides on data analysis, ML, and AI.
* [**Medium**](https://medium.com/): A knowledge base for technical topics and more.

---

# Documentation

* [**Markdown**](files/cheat_sheet_markdown.pdf): How to use the Markdown language to create documentation.
* [**Quarto**](files/cheat_sheet_quarto.pdf): A Markdown flavour with additional functionalities.

---

# YouTube Channels

* [**3Blue1Brown**](https://www.youtube.com/@3blue1brown): Visual explanations that make complex math and scientific concepts intuitive.
* [**Fireship**](https://www.youtube.com/@Fireship): High-intensity code tutorials and tech news.

---

# Visualisations

* [**The Wall Street journal guide to information graphics**](https://swisscovery.ch/permalink/41SLSP_NETWORK/19n6r1g/alma991066241679705501): Dos and dont's of presenting data.
