---
title: "Python for Data Science - Exercises"
toc: true
---

# Datatypes and Variables

## Exercises 1

### What does Python return as result of the following calculations?

```{python}
print(f"10 + 10 + 10 = {10 + 10 + 10}")
print(f"10 - 3       = {10 - 3}")
print(f"10 * 2       = {10 * 2}")
print(f"5 / 2        = {5 / 2}")
print(f"5.0 / 2      = {5.0 / 2}")
print(f"5 % 2        = {5 % 2}")
print(f"10 % 3       = {10 % 3}")
print(f"3 ** 3       = {3 ** 3}")
print(f"9 ** 0.5     = {9 ** 0.5}")
print(f"10 + 3 * 3   = {10 + 3 * 3}")
print(f"(10 + 3) * 3 = {(10 + 3) * 3}")

```

### Try to find out: What happens?

```{python}
a = 23
b = 23
print(f"a = {a}")
print(f"The ID of a is {id(a)}") # Prints memory address of the variable a
print(f"a is of type {type(a)}") # Prints the data type of the variable a
```

> Note: `id()` corresponds to the objects memory address during its lifetime.

```{python}
print(f"b = {b}")
print(f"The ID of b is {id(b)}")
print(f"b is of type {type(a)}")
```

### Change the value of variable "a"

```{python}
a = 123 # Reassign var a to int 123
print(f"a = {a}")
print(f"The ID of a is {id(a)}")
print(f"a is of type {type(a)}")
```

### What happens now? why?

```{python}
c = 23
print(f"c = {c}")
print(f"The ID of a is {id(c)}")
print(f"c is of type {type(c)}")
```

We assign the variable `c` to the value `23` and check its data type and memory location.

### Try the same thing with a float variable!!!

```{python}
d = 3.142
print(f"d = {d}")
print(f"The ID of a is {id(d)}")
print(f"d is of type {type(d)}")
```

### Printing of text (strings)

```{python}
print ("HSLU's Python course is cool")

print("This is Line 1")
print("This is Line 2")

print("\nWhat does the \\n control character do? Are you sure?") # \n is a line break

print("\tWhat does the \\t control character do? Are you sure?") # \t is a tabulator

print("I want to learn python because....")
print("\n\n\t....it's a cool data science programming language. Ok - there are also others ;-) !")

print("What " + "is " + "wrong?" + "\nAdd some space between the words without removing the '+' signs!") # Add spaces after the string
```

### try to understand the behaviour

```{python}
g=h='hslu'      # Assign the var g and h to the string "hslu"
print(g)        # Prints hslu
print(h)        # Print hslu
h=456           # Reassign h to int 456
print(h)        # Prints 456
h=h+1           # Calculates 456 + 1 = 457
print(h)        # Prints 457
h+=1            # Calculates 457 + 1 = 458
print(h)        # Prints 458
p='hslu'        # Assign the var p to the string "hslu"
q=p             # Copies the var p (hlsu) to the var q
print(p==q)     # Compare the var p and q (Output: True)
print(p is q)   # Compare the var p and q (Output: True)
```

# Conditions

## Task 1
Create a simple program in which three whole numbers (potentially negative!) are read in from the keyboard and afterwards get displayed on the screen in ascending order. Use nested if-statements for order determination (i.e. no built-in- 'sort' function).

### Using if-else-statements

```{python}
inputs = [] # Set up storage

print("Please input 3 whole numbers of your choise.")
"""
input1 = int(input("Number one: ")) # Assign input to a variable
input2 = int(input("Number two: "))
input3 = int(input("Number tree: "))
"""

# Use fake user inputs
input1 = -3
input2 = 10
input3 = -6

# Sort list
if input1 < input2 and input1 < input3:
    inputs.append(input1) # Append input to list
    if input2 < input3:
        inputs.append(input2)
        inputs.append(input3)
    else:
        inputs.append(input3)
        inputs.append(input2)
elif input2 < input1 and input2 < input3:
    inputs.append(input2)
    if input1 < input3:
        inputs.append(input1)
        inputs.append(input3)
    else:
        inputs.append(input3)
        inputs.append(input1)
elif input3 < input1 and input3 < input2:
    inputs.append(input3)
    if input1 < input2:
        inputs.append(input1)
        inputs.append(input2)
    else:
        inputs.append(input2)
        inputs.append(input1)

print(inputs)
```

### Using build in function `sorted()`

```{python}
inputs = [] # Set up storage

print("Please input 3 whole numbers of your choise.")
"""
input1 = int(input("Number one: ")) # Assign input to a variable
inputs.append(input1)
input2 = int(input("Number two: "))
inputs.append(input2)
input3 = int(input("Number tree: "))
inputs.append(input3)
"""

# Use fake user inputs
input1 = -3
inputs.append(input1)
input2 = 10
inputs.append(input2)
input3 = -6
inputs.append(input3)

# Sort list
inputs = sorted(inputs)
print(inputs)
```

## Task 2

### a
Assumption: The int variables a, b and c are declared and initialized.

Define a conditional expression "EXPR" in such a way that the body of the expression

if EXPR:
    print("condition fulfilled")

is only carried out if:
a is greater than b OR a is less than half of b OR the sum of a and c is greater than b.


Check your result:
a=1, b=2, c=2 -> True
a=1, b=2, c=1 -> False

```{python}
# Test case one
a = 1
b = 2
c = 2

if a > b or a < b/2 or sum([a, c]) > b:
    print("condition fulfilled")
else:
    print("condition not fulfilled")
```

```{python}
# Test case two
a = 1
b = 2
c = 1

if a > b or a < b/2 or sum([a, c]) > b:
    print("condition fulfilled")
else:
    print("condition not fulfilled")
```

### b

Assumption: The int variables a, b and c are declared and initialized.

Define a conditional expression "EXPR" in such a way that the body of the expression

if EXPR:
    print("condition fulfilled")

is only carried out if:
half of the number a is an odd number OR the subtraction of the numbers b and c results in an even number OR both a and b and also b and c have different values.

Check your result:
a=6, b=2, c=0 => True
a=5, b=2, c=1 => True
a=5, b=5, c=2 => False

```{python}
# Test case one
a = 6
b = 2
c = 0

if a/2 % 2 == 1 or b - c % 2 == 0 or a != b and b != c:
        print("condition fulfilled")
else:
    print("condition not fulfilled")
```

```{python}
# Test case two
# Test case one
a = 5
b = 2
c = 1

if a/2 % 2 == 1 or b - c % 2 == 0 or a != b and b != c:
        print("condition fulfilled")
else:
    print("condition not fulfilled")
```

```{python}
# Test case three
# Test case one
a = 5
b = 5
c = 2

if a/2 % 2 == 1 or b - c % 2 == 0 or a != b and b != c:
        print("condition fulfilled")
else:
    print("condition not fulfilled")
```

# Loops and Conditions

## Exercise 1

Write a python program that constructs the following pattern using a nested for loop:

```{txt}
*
**
***
****
*****
****
***
**
*
```

```{python}
upper  = range(0, 6, 1) # Define upper pattern
lower = range(6, 0, -1) # Define lower pattern


for i in upper:
    print("*" * i) # Print upper part of pattern
else: # After done
    for j in lower:
        print("*" * j) # Print lower part of pattern
```

## Exercise 2

Write a python program to count the number of even and odd numbers contained in a sequence of numbers.

```{python}
even_numbers = []
odd_numbers = []
numbers = (1,2,3,4,5,6,7,8,9,10)

for i in range(len(numbers)):
    if i % 2 == 0: # Check if current number is even
        even_numbers.append(i)
    else:
        odd_numbers.append(i)

print(f"Total number of even numbers: {len(even_numbers)}") # Use len() to count
print(f"Total number of even numbers: {len(odd_numbers)}")
```

## Exercise 3

Write a Python program which takes two digits m (row) and n (column) as input and
generates a two-dimensional structure (e.g. nested list). The value in the i-th row and j-th column 
should be i*j.

```{python}
rows = 3
columns = 4
result = [] # Define master list

for row in range(rows):
    sub_list = [] # Define sub-list
    for column in range(columns):
        sub_list.append(row * column) # Calc value
    result.append(sub_list) # Append sub-list to master list

print(result)
```

## Exercise 4
Write a Python program to find all numbers between 200 and 500 (limits included) only containing even digits.
Correct solution: 

```{python}
my_range = range(200, 501) # Include boarders
even_digit_numbers = [] # Final result

for number in my_range: 
    test_result = []
    for digit in str(number):
        if int(digit) % 2 == 1:
            test_result.append(True) # Add true for odd digit
        else:
            test_result.append(False) # Add false for even digit
    if any(test_result):
        pass # Pass if any odd digit (false) is in test_result
    else:
        even_digit_numbers.append(number) # Append to final result

print(even_digit_numbers)
```

## Exercise 5

Write a Python program to guess a number between 1 to 10.
First: Use the predefined code block to create a random number
Second:
The user is prompted to enter a guess. If the guess is wrong a message
"to big" or "to small" is printed to the console and the prompt (user
input) appears again until the guess is correct. If the guess is correct, "Well guessed!" will be printed and the program ends.
Extension:
The number of trials should be prompted as well: "Well done - you have tried it 4 times!"

```{python}
# Code block to create a random number
from random import randint
random_number = randint(1,10)
# End code block to create a random number

trials = 0

while True: # Infinitive loop till break
    # Unsing fake user input
    user_input = randint(1,10) # Also random
    trials += 1 # Count trials
    if user_input == random_number:
        print(f"Well done - you have tried it {trials} times!")
        break
    elif user_input < random_number:
        print("Guess to low...")
    else:
        print("Guess to high...")
```

## Exercise 6
Suppose we wish to draw a Christmas tree.
Example tree - desired height: 8
The result looks like:

```{txt}
     x
    xxx
   xxxxx
  xxxxxxx
 xxxxxxxxx
xxxxxxxxxxx
    xxx
    xxx
```

Create a program that asks the user for the height of the Christmas tree (trunk included)
and then draws the tree. The height of the trunk is always 2 and the width is 3 in case the entire height is > 5 and 1 in case the tree is smaller.

```{python}
total_height = 8
trunk_height = 2
crown_height = total_height - trunk_height
max_crown_width = 2 * (crown_height - 1) + 1

if total_height > 5:
    trunk_width = 3
else:
    trunk_width = 1

i = 0
while i < crown_height:
    current_crown_width = 2 * i + 1
    spaces = (max_crown_width - current_crown_width) // 2
    print(" " * spaces + "x" * current_crown_width)
    i += 1

trunk_padding = (max_crown_width - trunk_width) // 2

j = 0
while j < trunk_height:
    print(" " * trunk_padding + "x" * trunk_width)
    j += 1
```

# Debug

## Exercise 1

Write a Python program to guess a number between 1 to 10.
First: Use the predefined code block to create a random number
Second:
The user is prompted to enter a guess. If the guess is wrong a message
"to big" or "to small" is printed to the console and the prompt (user
input) appears again until the guess is correct. If the guess is correct, "Well guessed!" will be printed and the program ends.
Extension:
The number of trials should be prompted as well: "Well done - you have tried it 4 times!"

```{python}
# Code block to create a random number
from random import randint
random_number = randint(1,10)
# End code block to create a random number

trials = 0

while True: # Infinitive loop till break
    # Unsing fake user input
    user_input = randint(1,10) # Also random
    trials += 1 # Count trials
    if user_input == random_number:
        print(f"Well done - you have tried it {trials} times!")
        break
    elif user_input < random_number:
        print("Guess to low...")
    else:
        print("Guess to high...")
```

# Exercise Collection Functions

## Exercise 1

Write a function that accepts a list of integers as input and returns a list containing all even numbers of the input list.

```{python}
def extract_even_num(num_list: list[int]) -> list:
    """
    Returns all even numbers of within a given list

    Args:
        num_list: A list with integers.

    Returns:
        list: A list with all even numbers from num_list
    """
    even_num_list = [] # Result storage
    for num in num_list:
        if num % 2 == 0: # Check for even or odd
            even_num_list.append(num)
    
    return even_num_list # Return result

even_num = extract_even_num((1, 2, 3 ,4, 5, 6, 7, 8, 9))
print(even_num)
```

## Exercice 2

Write a function accepts a list as input and returns the unique values contained in that list as a list. Hint: you can use the "set" method to check your solution.

```{python}
def get_unique_values(value_list: list) -> set:
    """
    Return a set (unique values) from a given list

    Args:
        value_list: List with different values
    
    Returns:
        set: Unique values from value_list
    """
    return set(value_list)

uniques = get_unique_values((1, 2, 2, 3, "Hello", "Hello", "Bye"))
print(uniques)
```

## Exercise 3

Crate a simple calculator that provides functions to add, subtract, multiply and divide two numbers.
Implement the missing parts to execute the main() function below without an error.

```{python}
def add(num1: int, num2: int) -> int:
    """ Add two numbers """
    return num1 + num2

def subtract(num1: int, num2: int) -> int:
    """ Subtract two numbers """
    return num1 - num2

def multiply(num1: int, num2: int) -> int:
    """ Multiply two numbers """
    return num1 * num2

def divide(num1: int, num2: int) -> int:
    """ Divide two numbers """
    return num1 / num2

def main():
    print("Select operation.")
    print("1.Add")
    print("2.Subtract")
    print("3.Multiply")
    print("4.Divide")

    # Take input from the user
    # choice = input("Enter choice(1/2/3/4):")
    # Using fake user inputs
    choice = str(1)

    # num1 = int(input("Enter first number: "))
    # num2 = int(input("Enter second number: "))
    # Using fake user inputs

    num1 = 4
    num2 = 5

    if choice == '1':
       print(num1,"+",num2,"=", add(num1,num2))

    elif choice == '2':
       print(num1,"-",num2,"=", subtract(num1,num2))

    elif choice == '3':
       print(num1,"*",num2,"=", multiply(num1,num2))

    elif choice == '4':
       print(num1,"/",num2,"=", divide(num1,num2))
    else:
       print("Invalid input")

main()
```

## Extercise 4

Keyword parameters
If we want call the function circumference(2) with the 'width' 2
we have a problem: The number '2' is by default assigned to the first
Parameter and that is 'length' ... Task: Change the calls so that the function circumference(2) is called with 'width' 2!

```{python}
def circumference(length = 2, width = 1):
     return 2 * (length + width)

c1 = circumference(width=2)         # 2 should be the width !!!
print(c1)

# or with length 5 and width 3:
c2 = circumference(5, 3)
print(c2)

# how could the function also have been called
# with length 5 and width 3
c3 = circumference(length=5, width=3)
print(c3)

# you can even change the order of keyword parameters
# try it: Change the order of  parameters!
c4 = circumference (width=3, length=5)     # order swapped!
print(c4)
```

## Exercise 5

Functions may have parameters which may have default values.

Task: Change the two examples (1 and 2) such that the two function calls hello(...)
and the three function calls circumference(...) run without any error.

```{python}
# Example 1:
def hello (name = "Mr. Unknown"):
     print ("Hello " + name + "!")

hello("Peter")

# without parameters (default value used)
hello()


# Example 2:
def circumference (length=1, width=1):
     return 2 * (length + width)

c1 = circumference(5, 3)
print(c1)

# for the width, the default value "1" is used.
c2 = circumference(5)
print(c2)

# both default values are used.
c3 = circumference()
print(c3)
```

# Exercise Collection File Access

## Exercise 01

Write a program that combines three lines from the file 'musicians.txt' into one line
and writes them as standard output using print(). That means: An output line should contain: first name, last name and artist name ("Künstername") or band of the artist. The band or artist name should be printed in round brackets and in captial letters. Example: "Marshall Bruce Mathers III (EMINEM)"

```{python}
with open('data/musicians.txt', mode='r') as file: # Read file
        musicians = [line.rstrip() for line in file]

first_name = 0
artist_name = 1
band = 2

while band < len(musicians):
    print(f"{musicians[first_name]} {musicians[artist_name]} ({str.upper(musicians[band])})")

    first_name += 3
    artist_name += 3
    band += 3
```

## Exercise 02

Change the solution of Exercise 02 so that the program writes the output to the file 'musicians2.txt'.

```{python}
with open('data/musicians.txt', mode='r') as file: # Read file
        musicians = [line.rstrip() for line in file]

first_name = 0
artist_name = 1
band = 2

while band < len(musicians):
    with open('data/musicians2.txt', mode='a') as file2: # Mode = Append
        file2.write(f"{musicians[first_name]} {musicians[artist_name]} ({str.upper(musicians[band])})\n")

    first_name += 3
    artist_name += 3
    band += 3
```

# Exercise Collection String Formatting

## Exercise 01

Use the f"XXX" syntax to produce the following print out "Hello Andreas and Ramon!" based on the given varibles.

```{python}
var1 = "and"
var2 = "Andreas"
var3 = "!"
var4 = "Hello"
var5 = "Ramon"

print(f"{var4} {var2} {var1} {var5}{var3}")
```

## Exercise 02

Use the "XXX".format() syntax to produce the following print out: "My name is Giacomo, I am 10 years old, and I live in Padova."
based on the given dictionary. In the formatting call use:
1 order based
2 numbering based
3 key word based
4 dictionary key based
versions to insert the variables.

```{python}
insert_dict = {'name': 'Giacomo', 'age': 10, 'city': 'Padova'}

# Order based
print("My name is {}, I am {} years old, and I live in {}.".format(
    insert_dict['name'], insert_dict['age'], insert_dict['city']
))

# Numbering based
print("My name is {0}, I am {1} years old, and I live in {2}.".format(
    insert_dict['name'], insert_dict['age'], insert_dict['city']
))

# Key word based
print("My name is {n}, I am {a} years old, and I live in {c}.".format(
    n=insert_dict['name'], a=insert_dict['age'], c=insert_dict['city']
))

# Dictionary key based
print("My name is {name}, I am {age} years old, and I live in {city}.".format(
    **insert_dict
))
```

## Exercise 03

You are given list of n (even) numbers. Write a program that prints for each pair [(first, last), (second, second last ), etc...] X and Y the following string: X times Y is: X*Y. Use in place calculations to calculate the product directly in the string within the print statement.

```{python}
nums = [1, 2, 3, 4, 5, 6]

for i in range(len(nums)):
    print(f"{nums[i] * nums[len(nums) - 1 - i]}")
```

# Exercise kwargs

Write a function that accepts an arbitrary number of keyword arguments. The function should number each keyword-value pair and print it in the following format:
1: keyword -> value
2: keyword -> value
...
n: keyword -> value

```{python}
def print_pairs(**kwargs): # Takes n parameters
    # Iterate over dict 
    for i, (key, value) in enumerate(kwargs.items(), start=1):
        print(f"{i}: {key} -> {value}")

print_pairs(first=1, second=2, third=3)
```

# Exercise Animals

## Part a

For each animal, print "Hi, I'm a {animal_type} and my name is {name}!" Solve the exercise by writing a class 'Animal' and adding a method allowing to print the requested string. Note that it is not necessary for this task, to differentiate between animal types!

```{python}
print("Part a): \n\n")

class Animal:

    def __init__(self, animal_type, name, age, weight, legs):
        self.animal_type = animal_type
        self.name = name
        self.age = age
        self.weight = weight
        self.legs = legs

    def __str__(self):
        return(f"Hi, I'm a {self.animal_type} and my name is {self.name}!")

with open('data/animals.csv') as f:
    for line in f.readlines()[1:]:
        animal_type = line.split(", ")[0]
        name = line.split(", ")[1]
        age = int(line.split(", ")[2])
        weight = int(line.split(", ")[3])
        legs = int(line.split(", ")[4])
        #create objects
        obj = Animal(animal_type, name, age, weight, legs)
        print(obj)
```

## Part b

Now we are interested in the various sounds the animal types make. Write a separate class for each animal type. Provide a method "speak", which depending on the animal type prints different sounds.

```{python}
print("\n\nPart b): \n\n")

class Dog():

    def __init__(self, name, age, weight, legs):
        self.name = name
        self.age = age
        self.weight = weight
        self.legs = legs

    def speak(self):
        return "Whuff whuff!"

class Cat():

    def __init__(self, name, age, weight, legs):
        self.name = name
        self.age = age
        self.weight = weight
        self.legs = legs

    def speak(self):
        return "Mew mew!"

class Snake():

    def __init__(self, name, age, weight, legs):
        self.name = name
        self.age = age
        self.weight = weight
        self.legs = legs

    def speak(self):
        return "Sssssss!"


# solution with file loop
obj_list = []
with open('data/animals.csv') as f:
    for line in f.readlines()[1:]:
        animal_type = line.split(", ")[0]
        name = line.split(", ")[1]
        age = int(line.split(", ")[2])
        weight = int(line.split(", ")[3])
        legs = int(line.split(", ")[4])
        #create objects
        if animal_type == 'dog':
            obj = Dog(name, age, weight, legs)
            obj_list.append(obj)
        if animal_type == 'cat':
            obj = Cat(name, age, weight, legs)
            obj_list.append(obj)
        if animal_type == 'snake':
            obj = Snake(name, age, weight, legs)
            obj_list.append(obj)

for elem in obj_list:
    print(elem.speak())
```

# Exercise Animals Inheritance

## Part a

Produce a class structure where Dog, Cat and Snake are implemented as child classes of a base class Animal. Create the object variables in the base class, along with a method 'print_basic_information', which prints 'type' and 'name' to the console. In each child class, use the base class constructor with 'super' and add an additional method 'speak', specific to that child class. In each child class, add an additional method where you return the sum of the object variables 'age' and 'legs'.

For each element in the animals.csv, create an object of the corresponding subclass, let it print basic information (method from 'Animal'), let it speak (method from child class) and get the sum of 'age' and 'legs' as a return value.

```{python}
class Animal:
    def __init__(self, animal_type: str, name: str, age: int, weight: int, legs: int):
        self.animal_type = animal_type
        self.name = name
        self.age = age
        self.weight = weight
        self.legs = legs

    def print_basic_information(self):
        print(f"Type = {self.animal_type} and name = {self.name}")

class Dog(Animal):

    def __init__(self, animal_type: str, name: str, age: int, weight: int, legs: int):
        super().__init__(animal_type, name, age, weight, legs)

    def speak(self):
        return "Wuff"

    def sum_of_age_and_legs(self):
        return sum([self.age, self.legs])

class Cat(Animal):

    def __init__(self, animal_type: str, name: str, age: int, weight: int, legs: int):
        super().__init__(animal_type, name, age, weight, legs)

    def speak(self):
        return "Meww"

    def sum_of_age_and_legs(self):
        return sum([self.age, self.legs])

class Snake(Animal):

    def __init__(self, animal_type: str, name: str, age: int, weight: int, legs: int):
        super().__init__(animal_type, name, age, weight, legs)

    def speak(self):
        return "Ssss"

    def sum_of_age_and_legs(self):
        return sum([self.age, self.legs])

obj_list = []
with open('./data/animals.csv') as f:
    for line in f.readlines()[1:]:
        animal_type = line.split(", ")[0]
        name = line.split(", ")[1]
        age = int(line.split(", ")[2])
        weight = int(line.split(", ")[3])
        legs = int(line.split(", ")[4])
        # create objects based on animal_type
        if animal_type == "dog":
            obj = Dog(animal_type=animal_type, name=name, age=age, weight=weight, legs=legs)
        elif animal_type == "cat":
            obj = Cat(animal_type=animal_type, name=name, age=age, weight=weight, legs=legs)
        else:
            obj = Snake(animal_type=animal_type, name=name, age=age, weight=weight, legs=legs)
        # add objects to obj_list
        obj_list.append(obj)

for elem in obj_list:
    print("--\n")
    elem.print_basic_information()
    elem.speak()
    c_sum = elem.sum_of_age_and_legs()
    print(c_sum)
```

## Part b

```{python}
class Animal:
    def __init__(self, animal_type: str, name: str, age: int, weight: int, legs: int, sound: str):
        self.animal_type = animal_type
        self.name = name
        self.age = age
        self.weight = weight
        self.legs = legs
        self.sound = sound

    def print_basic_information(self):
        print(f"Type = {self.animal_type} and name = {self.name}")
    
    def sum_of_age_and_legs(self):
        return sum([self.age, self.legs])

    def speak(self):
        print(self.sound)

class Dog(Animal):

    def __init__(self, animal_type: str, name: str, age: int, weight: int, legs: int, sound: str):
        super().__init__(animal_type, name, age, weight, legs, sound)

class Cat(Animal):

    def __init__(self, animal_type: str, name: str, age: int, weight: int, legs: int, sound: str):
        super().__init__(animal_type, name, age, weight, legs, sound)

class Snake(Animal):

    def __init__(self, animal_type: str, name: str, age: int, weight: int, legs: int, sound: str):
        super().__init__(animal_type, name, age, weight, legs, sound)

obj_list = []
with open('./data/animals.csv') as f:
    for line in f.readlines()[1:]:
        animal_type = line.split(", ")[0]
        name = line.split(", ")[1]
        age = int(line.split(", ")[2])
        weight = int(line.split(", ")[3])
        legs = int(line.split(", ")[4])
        # create objects based on animal_type
        if animal_type == "dog":
            obj = Dog(animal_type=animal_type, name=name, age=age, weight=weight, legs=legs, sound= "Wuff")
        elif animal_type == "cat":
            obj = Cat(animal_type=animal_type, name=name, age=age, weight=weight, legs=legs, sound="Meww")
        else:
            obj = Snake(animal_type=animal_type, name=name, age=age, weight=weight, legs=legs, sound="Ssss")
        # add objects to obj_list
        obj_list.append(obj)

for elem in obj_list:
    print("--\n")
    elem.print_basic_information()
    elem.speak()
    c_sum = elem.sum_of_age_and_legs()
    print(c_sum)
```

## Part c

```{python}
class Animal:
    def __init__(self, animal_type: str, name: str, age: int, weight: int, legs: int, sound: str):
        self.animal_type = animal_type
        self.name = name
        self.age = age
        self.weight = weight
        self.legs = legs
        self.sound = sound

    def print_basic_information(self):
        print(f"Type = {self.animal_type} and name = {self.name}")
    
    def sum_of_age_and_legs(self):
        return sum([self.age, self.legs])

    def speak(self):
        print(self.sound)

class Dog(Animal):

    def __init__(self, animal_type: str, name: str, age: int, weight: int, legs: int, sound: str):
        super().__init__(animal_type, name, age, weight, legs, sound)

    def print_basic_information(self):
        print(self.__class__.__name__)

class Cat(Animal):

    def __init__(self, animal_type: str, name: str, age: int, weight: int, legs: int, sound: str):
        super().__init__(animal_type, name, age, weight, legs, sound)

class Snake(Animal):

    def __init__(self, animal_type: str, name: str, age: int, weight: int, legs: int, sound: str):
        super().__init__(animal_type, name, age, weight, legs, sound)

obj_list = []
with open('./data/animals.csv') as f:
    for line in f.readlines()[1:]:
        animal_type = line.split(", ")[0]
        name = line.split(", ")[1]
        age = int(line.split(", ")[2])
        weight = int(line.split(", ")[3])
        legs = int(line.split(", ")[4])
        # create objects based on animal_type
        if animal_type == "dog":
            obj = Dog(animal_type=animal_type, name=name, age=age, weight=weight, legs=legs, sound= "Wuff")
        elif animal_type == "cat":
            obj = Cat(animal_type=animal_type, name=name, age=age, weight=weight, legs=legs, sound="Meww")
        else:
            obj = Snake(animal_type=animal_type, name=name, age=age, weight=weight, legs=legs, sound="Ssss")
        # add objects to obj_list
        obj_list.append(obj)

for elem in obj_list:
    print("--\n")
    elem.print_basic_information()
    elem.speak()
    c_sum = elem.sum_of_age_and_legs()
    print(c_sum)
```