---
title: Discrete Response, Time Series and Panel Data - Exercise 02
author: Nils Rechberger
date: 2026-05-31
execute:
  warning: false
  message: false
---

# Series 2

## Exercise 2.1

### A

```{r}
# create timeseries object
t <- seq(1, 100, length = 100)
data <- 0.5 * t + 1 + runif(100, -1, 1)

ts <- ts(data)
plot(ts)
length(ts)

# Applying backward differencing
ts.2 <- diff(ts, lag = 1)
plot(ts.2)
length(ts.2)
```

The new time series are 99 units long instead of 100.

### B

```{r}
# create timeseries object
t <- seq(1, 100, length = 100)
data <- 2 * t **2 + 3 * t - 1 + runif(100, -200, 200)

ts <- ts(data)
plot(ts)
length(ts)

# Applying backward differencing
ts.2 <- diff(ts, lag = 1)
plot(ts.2)
length(ts.2)

# Again Applying backward differencing
ts.3 <- diff(ts.2, lag = 1)
plot(ts.3)
length(ts.3)
```

Since we applied backward differencing twice, the length of the output time series increased to 98.

## Exercise 2.2

### A

```{r}
hstart <- read.table("/home/nils/dev/mscids-notes/sp26/rtp/data/hstart.dat")

ts <- ts(hstart[, 1], start = c(1966, 1), frequency = 12)
hstart_stl <- stl(ts, s.window = "periodic")

plot(hstart_stl)
```

### B

```{r}
hstart <- read.table("/home/nils/dev/mscids-notes/sp26/rtp/data/hstart.dat")

ts <- ts(hstart[, 1], start = c(1966, 1), frequency = 12)

weights <- c(1, rep(2, 11), 1) / 24
filtered <- filter(ts, filter = weights)

plot(ts)
points(filtered, type = "l", col = "blue")
lines(hstart_stl$time.series[, "trend"], col = "red")
```

### C

```{r}
hstart <- read.table("/home/nils/dev/mscids-notes/sp26/rtp/data/hstart.dat")

ts <- ts(hstart[, 1], start = c(1966, 1), frequency = 12)
plot(ts)

ts.2 <- diff(ts, lag=12) # Using lag 12 bc 12 months per year
plot(ts.2)
```

## Exercise 2.3

```{r}
data(co2)
plot(diff(co2, 1), type = "n", ylim = c(-5, 15))

for (l in 1:12) {
    ts_diff <- diff(co2, lag = l)
    lines(ts_diff, col = rainbow(12)[l])
}
legend("topleft", legend = paste("Lag", 1:12), col = rainbow(12), lty = 1, ncol = 2)
```
