---
title: Discrete Response, Time Series and Panel Data - Exercise 08
author: Nils Rechberger
date: 2026-05-31
execute:
  warning: false
  message: false
---

# Series 8

## Exercise 8.1

### A

```r
arima.1 <-arima.sim(
    n=250,
    order=c(2, 1, 2),
    list(
        ar=c(0.5, 0,5),ma=c(-0.4, 0.3)
        )
    )
```

The problem: `ar` part of model is not stationary!

### B

```{r}
# 1. Define the coefficients as polynomials: c(1, -coef1, -coef2)
ar_poly <- c(1, -0.5, -0.5) 
diff_poly <- c(1, -1)       

# 2. Multiply the polynomials using convolution
# We reverse the second vector (diff_poly) because of how convolve() calculates
arma_ar_poly <- convolve(ar_poly, rev(diff_poly), type = "open")

# View the resulting polynomial: 1 - 1.5*B + 0*B^2 + 0.5*B^3
print(arma_ar_poly) 
# Output: [1]  1.0 -1.5  0.0  0.5

# 3. Extract the ARMA coefficients
# Drop the intercept (the first '1') and flip the signs back to standard AR format
arma_ar_coefs <- -arma_ar_poly[-1]

# 4. The MA coefficients remain identical to the original ARIMA model
arma_ma_coefs <- c(-0.4, 0.3)

# Print final coefficients
cat("Equivalent ARMA AR coefficients:", arma_ar_coefs, "\n")
cat("Equivalent ARMA MA coefficients:", arma_ma_coefs, "\n")
```

## Exercise 8.2

```{r}
d.beluga <- read.table("http://stat.ethz.ch/Teaching/Datasets/WBL/beluga.dat", header = TRUE)
d.beluga <- ts(d.beluga)
```

### A

```{r}
y = lm(NURSING ~ ., data=d.beluga)
y
```

```{r}
plot(y$res, type="l")
abline(h=0, col="red")
```

### B

``` r
acf(d.beluga)
```

```{r}
r.burg <- ar(
    x=d.beluga,
    order.max=8
    )
plot(r.burg$res)
```

### C

```{r}
library(nlme) # Load the package containing the procedure gls()

r.bel.gls <- gls(
    NURSING ~ BOUTS + LOCKONS + DAYNIGHT + PERIOD,
    data = d.beluga,
    correlation = corARMA(
        form = ~PERIOD,
        p = r.burg$order,
        q = 0,
        fixed = FALSE
    ),
    method = "ML"
    )

summary(r.bel.gls)
d.resid <- ts(resid(r.bel.gls))
```

## Exercise 8.3

### A

```{r}
t.url <- "http://stat.ethz.ch/Teaching/Datasets/WBL/varve.dat"
d.varve <- ts(scan(t.url)[201:550])
```

```{r}
acf(diff(log(d.varve)))
```

```{r}
pacf(log(d.varve))
```


```{r}
r.varve <- arima(
    x=log(d.varve),
    order = c(2, 1, 2),
    method="ML"
    )
r.varve
```

### B

$$
y = -0.1442\alpha_1 + 0.1452\alpha_2 + -0.5334\beta_1 + -0.3548\beta_2 + \varepsilon_0
$$
