---
title: Discrete Response, Time Series and Panel Data - Exercise 10
author: Nils Rechberger
date: 2026-05-31
execute:
  warning: false
  message: false
---

# Series 10

## Exercise 10.1

```{r}
library(fpp2)

lsunspot100 <- window(log(sunspotarea), start = 1875, end = 1974)
fit.ar10 <- arima(lsunspot100, order = c(10, 0, 0))
fit.ar10
```

### A

```{r}
pred <- predict(fit.ar10, n.ahead = 100)

plot(x=lsunspot100, xlim = c(1875, 2074))
abline(h = fit.ar10$coef["intercept"], lty = 2)
lines(pred$pred, col = "green")
```

### B

```{r}
pred_b <- predict(fit.ar10, n.ahead = 37)

plot(lsunspot100, 
     main = "Log-Transformed Sunspot Area with AR(10) Predictions",
     ylab = "Log(Area)", 
     xlab = "Year",
     xlim = c(1875, 2015))
lines(pred_b$pred, col = "blue", lwd = 2)
lines(pred_b$pred + 1.96 * pred_b$se, col = "red", lty = 2)
lines(pred_b$pred - 1.96 * pred_b$se, col = "red", lty = 2)

# 6. Calculate the Mean Squared Forecasting Error (MSFE)
# Extract the actual observed values for the out-of-sample period (1975-2011)
actual_out_of_sample <- window(sunspotarea, start = 1975, end = 2011)

# Compute the Mean Squared Error between actuals and predictions
msfe <- mean((actual_out_of_sample - pred_b$pred)^2)

cat("Mean Squared Forecasting Error (MSFE):", msfe, "\n")
```

## Exercise 10.2

```{r}
data("AirPassengers")
d.air <- AirPassengers
d.airshort <- window(d.air, end = c(1956, 12))
plot(d.airshort)
```

### A

```{r}
d.airshort.trans <- diff(log(d.airshort))
fit <- auto.arima(d.airshort.trans, ic="aic")

#Perform forecast
fc <- predict(fit, n.ahead=4*12)

#Plot everything
plot(
    x=d.airshort.trans,
    lty=3,
    xlim=c(1957,1960)
    )
lines(d.airshort, lwd=1)
lines(fc$pred, lwd=2, col="red")
lines(fc$pred+fc$se*1.96, col="blue")
lines(fc$pred-fc$se*1.96, col="blue")
```
