{
  "hash": "fceea82a4bf16594c0b258daf2649d83",
  "result": {
    "engine": "knitr",
    "markdown": "---\ntitle: Discrete Response, Time Series and Panel Data - Exercises\nauthor: Nils Rechberger\ndate: 2026-03-05\nexecute:\n  warning: false\n  message: false\n---\n\n\n\n\n\n\n# Series 1\n\n## Exercise 1.1\n\nWhat is the expected period (time period of repetition) and the time step for the following timeseries:\n\n- Sunshine duration per month in Basel from 1990 to 2000: Timestep = 1 month, Period = 12 months.\n- Number of newborn babies in the city of Zurich per year from 2000 to 2011: Timestep = 1 year, Periode = None.\n- Number of reservations in a restaurant for every night during 4 weeks: Timestep = 1 day, Periode = 7 days.\n- Water runoff of a river. The data has been collected every day for 4 years: Time step = 1, periode = 365 days.\n\n## Exercise 1.2\n\n\n\n\n\n\n::: {.cell}\n\n```{.r .cell-code}\nhstart <- read.table(\"/home/nils/dev/mscids-notes/fs26/rtp/data/hstart.dat\")\n\nts <- ts(hstart,start=c(1966,1),freq=12)\n\nplot(ts, main=\"Residential construction in the USA\")\n```\n\n::: {.cell-output-display}\n![](rtp_exercises_files/figure-pdf/unnamed-chunk-1-1.pdf){fig-pos='H'}\n:::\n:::\n\n\n\n\n\n\nThis is not a stationary time series. A stationary time series is one whose statistical properties (mean, variance, etc) are constant over time. This data fails that definition due to two distinct types of non-stationarity.\n\n- Trend: The long-term \"level\" of the data shifts upward and then downward.\n- Seasonality: There are recurring annual cycles.\n- Changing Variance: The intensity of the fluctuations changes over the years.\n\n## Exercises 1.3\n\n### A\n\n\n\n\n\n::: {.cell}\n\n```{.r .cell-code}\nset.seed(1)\n\nEt <- ts(rnorm(101, 0, 1))\n\nEt[1] <- 0\ny1 <- 0 #delete later\n\nfor (i in 2:length(Et)) {\n    y1[i-1] <- Et[i] - 0.5 * Et[i-1]\n}\n\ny1 = y1[2:length(y1)]\nts.y1 = ts(y1)\n\nplot(ts.y1, main=\"Simulated Time Series Y1\", ylab=\"Y_t\", xlab=\"Time\")\nabline(h=0, col=\"red\", lty=2)\n```\n\n::: {.cell-output-display}\n![](rtp_exercises_files/figure-pdf/unnamed-chunk-2-1.pdf){fig-pos='H'}\n:::\n:::\n\n\n\n\n\n\nThe time series seems to be stationary.\n\n### B\n\n\n\n\n\n\n::: {.cell}\n\n```{.r .cell-code}\nset.seed(1)\n\nEt <- ts(rnorm(101, 0, 1))\n\nEt[1] <- 0\ny1 <- 0 #delete later\n\nfor (i in 2:length(Et)) {\n    y1[i] <- y1[i-1] + Et[i]\n}\n\ny1 = y1[2:length(y1)]\nts.y1 = ts(y1)\n\nplot(ts.y1, main=\"Simulated Time Series Y2\", ylab=\"Y_t\", xlab=\"Time\")\nabline(h=0, col=\"red\", lty=2)\n```\n\n::: {.cell-output-display}\n![](rtp_exercises_files/figure-pdf/unnamed-chunk-3-1.pdf){fig-pos='H'}\n:::\n:::\n\n\n\n\n\n\nThe time series seems not to be stationary.\n\n### C\n\n\n\n\n\n\n::: {.cell}\n\n```{.r .cell-code}\nset.seed(1)\n\nEt <- ts(rnorm(101, 0, 1))\n\nEt[1] <- 0\ny1 <- 0 #delete later\n\nfor (i in 2:length(Et)) {\n    y1[i] <- 0.5 * y1[i-1] + Et[i]\n}\n\ny1 = y1[2:length(y1)]\nts.y1 = ts(y1)\n\nplot(ts.y1, main=\"Simulated Time Series Y3\", ylab=\"Y_t\", xlab=\"Time\")\nabline(h=0, col=\"red\", lty=2)\n```\n\n::: {.cell-output-display}\n![](rtp_exercises_files/figure-pdf/unnamed-chunk-4-1.pdf){fig-pos='H'}\n:::\n:::\n\n\n\n\n\n\nThe time series seems to be stationary.\n\n### D\n\n\n\n\n\n\n::: {.cell}\n\n```{.r .cell-code}\nset.seed(1)\n\nEt <- ts(runif(101, 0.95, 1.05))\n\nEt[1] <- 0\ny1 <- 1 #delete later\n\nfor (i in 2:length(Et)) {\n    y1[i] <- y1[i-1] * Et[i]\n}\n\ny1 = y1[2:length(y1)]\nts.y1 = ts(y1)\n\nplot(ts.y1, main=\"Simulated Time Series Y2\", ylab=\"Y_t\", xlab=\"Time\")\nabline(h=0, col=\"red\", lty=2)\n```\n\n::: {.cell-output-display}\n![](rtp_exercises_files/figure-pdf/unnamed-chunk-5-1.pdf){fig-pos='H'}\n:::\n:::\n\n\n\n\n\n\nThe time series seems not to be stationary.\n\n# Series 2\n\n## Exercise 2.1\n\n### A\n\n\n\n\n\n\n::: {.cell}\n\n```{.r .cell-code}\n# create timeseries object\nt <- seq(1, 100, length = 100)\ndata <- 0.5 * t + 1 + runif(100, -1, 1)\n\nts <- ts(data)\nplot(ts)\n```\n\n::: {.cell-output-display}\n![](rtp_exercises_files/figure-pdf/unnamed-chunk-6-1.pdf){fig-pos='H'}\n:::\n\n```{.r .cell-code}\nlength(ts)\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n[1] 100\n```\n\n\n:::\n\n```{.r .cell-code}\n# Applying backward differencing\nts.2 <- diff(ts, lag = 1)\nplot(ts.2)\n```\n\n::: {.cell-output-display}\n![](rtp_exercises_files/figure-pdf/unnamed-chunk-6-2.pdf){fig-pos='H'}\n:::\n\n```{.r .cell-code}\nlength(ts.2)\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n[1] 99\n```\n\n\n:::\n:::\n\n\n\n\n\n\nThe new time series are 99 units long instead of 100.\n\n### B\n\n\n\n\n\n\n::: {.cell}\n\n```{.r .cell-code}\n# create timeseries object\nt <- seq(1, 100, length = 100)\ndata <- 2 * t **2 + 3 * t - 1 + runif(100, -200, 200)\n\nts <- ts(data)\nplot(ts)\n```\n\n::: {.cell-output-display}\n![](rtp_exercises_files/figure-pdf/unnamed-chunk-7-1.pdf){fig-pos='H'}\n:::\n\n```{.r .cell-code}\nlength(ts)\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n[1] 100\n```\n\n\n:::\n\n```{.r .cell-code}\n# Applying backward differencing\nts.2 <- diff(ts, lag = 1)\nplot(ts.2)\n```\n\n::: {.cell-output-display}\n![](rtp_exercises_files/figure-pdf/unnamed-chunk-7-2.pdf){fig-pos='H'}\n:::\n\n```{.r .cell-code}\nlength(ts.2)\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n[1] 99\n```\n\n\n:::\n\n```{.r .cell-code}\n# Again Applying backward differencing\nts.3 <- diff(ts.2, lag = 1)\nplot(ts.3)\n```\n\n::: {.cell-output-display}\n![](rtp_exercises_files/figure-pdf/unnamed-chunk-7-3.pdf){fig-pos='H'}\n:::\n\n```{.r .cell-code}\nlength(ts.3)\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n[1] 98\n```\n\n\n:::\n:::\n\n\n\n\n\n\nSince we applied backward differencing twice, the length of the output time series increased to 98.\n\n## Exercise 2.2\n\n### A\n\n\n\n\n\n\n::: {.cell}\n\n```{.r .cell-code}\nhstart <- read.table(\"/home/nils/dev/mscids-notes/fs26/rtp/data/hstart.dat\")\n\nts <- ts(hstart[, 1], start = c(1966, 1), frequency = 12)\nhstart_stl <- stl(ts, s.window = \"periodic\")\n\nplot(hstart_stl)\n```\n\n::: {.cell-output-display}\n![](rtp_exercises_files/figure-pdf/unnamed-chunk-8-1.pdf){fig-pos='H'}\n:::\n:::\n\n\n\n\n\n\n### B\n\n\n\n\n\n\n::: {.cell}\n\n```{.r .cell-code}\nhstart <- read.table(\"/home/nils/dev/mscids-notes/fs26/rtp/data/hstart.dat\")\n\nts <- ts(hstart[, 1], start = c(1966, 1), frequency = 12)\n\nweights <- c(1, rep(2, 11), 1) / 24\nfiltered <- filter(ts, filter = weights)\n\nplot(ts)\npoints(filtered, type = \"l\", col = \"blue\")\nlines(hstart_stl$time.series[, \"trend\"], col = \"red\")\n```\n\n::: {.cell-output-display}\n![](rtp_exercises_files/figure-pdf/unnamed-chunk-9-1.pdf){fig-pos='H'}\n:::\n:::\n\n\n\n\n\n\n### C\n\n\n\n\n\n\n::: {.cell}\n\n```{.r .cell-code}\nhstart <- read.table(\"/home/nils/dev/mscids-notes/fs26/rtp/data/hstart.dat\")\n\nts <- ts(hstart[, 1], start = c(1966, 1), frequency = 12)\nplot(ts)\n```\n\n::: {.cell-output-display}\n![](rtp_exercises_files/figure-pdf/unnamed-chunk-10-1.pdf){fig-pos='H'}\n:::\n\n```{.r .cell-code}\nts.2 <- diff(ts, lag=12) # Using lag 12 bc 12 months per year\nplot(ts.2)\n```\n\n::: {.cell-output-display}\n![](rtp_exercises_files/figure-pdf/unnamed-chunk-10-2.pdf){fig-pos='H'}\n:::\n:::\n\n\n\n\n\n\n## Exercise 2.3\n\n\n\n\n\n\n::: {.cell}\n\n```{.r .cell-code}\ndata(co2)\nplot(diff(co2, 1), type = \"n\", ylim = c(-5, 15))\n\nfor (l in 1:12) {\n    ts_diff <- diff(co2, lag = l)\n    lines(ts_diff, col = rainbow(12)[l])\n}\nlegend(\"topleft\", legend = paste(\"Lag\", 1:12), col = rainbow(12), lty = 1, ncol = 2)\n```\n\n::: {.cell-output-display}\n![](rtp_exercises_files/figure-pdf/unnamed-chunk-11-1.pdf){fig-pos='H'}\n:::\n:::\n\n\n\n\n\n\n# Series 3\n\n## Exercise 3.1\n\n- A -> 2\n- B -> 3\n- C -> 1\n- D -> 4\n\n## Exercise 3.2\n\n\n\n\n\n\n::: {.cell}\n\n```{.r .cell-code}\ncbe <- read.table(\"/home/nils/dev/mscids-notes/fs26/rtp/data/cbe.dat\", header = TRUE)\nts <- ts(cbe$elec,  start = c(1958, 1), frequency = 12)\nplot(ts)\n```\n\n::: {.cell-output-display}\n![](rtp_exercises_files/figure-pdf/unnamed-chunk-12-1.pdf){fig-pos='H'}\n:::\n:::\n\n\n\n\n\n\n### A \n\nAt this time, it is not advisable to examine the ACF because the time series is not stationary. We can see trends and seasonality over time. We need to clean that up first before analysing the time series.\n\n### B\n\n\n\n\n\n\n::: {.cell}\n\n```{.r .cell-code}\ndecomp <- decompose(ts, type = \"multiplicative\")\nacf(decomp$random, na.action = na.pass)\n```\n\n::: {.cell-output-display}\n![](rtp_exercises_files/figure-pdf/unnamed-chunk-13-1.pdf){fig-pos='H'}\n:::\n:::\n\n\n\n\n\n\n### C\n\n\n\n\n\n\n::: {.cell}\n\n```{.r .cell-code}\nts.stl.1 <- stl(log(ts), s.window = \"periodic\")\nplot(ts.stl.1$time.series[, \"trend\"])\n```\n\n::: {.cell-output-display}\n![](rtp_exercises_files/figure-pdf/unnamed-chunk-14-1.pdf){fig-pos='H'}\n:::\n\n```{.r .cell-code}\ndecomp <- decompose(ts.stl.1$time.series[, \"trend\"], type = \"multiplicative\")\nacf(decomp$random, na.action = na.pass)\n```\n\n::: {.cell-output-display}\n![](rtp_exercises_files/figure-pdf/unnamed-chunk-14-2.pdf){fig-pos='H'}\n:::\n:::\n\n::: {.cell}\n\n```{.r .cell-code}\nmonthplot(ts)\n```\n\n::: {.cell-output-display}\n![](rtp_exercises_files/figure-pdf/unnamed-chunk-15-1.pdf){fig-pos='H'}\n:::\n\n```{.r .cell-code}\nts.stl.2 <- stl(log(ts), s.window = 12)\nplot(ts.stl.2$time.series[, \"trend\"])\n```\n\n::: {.cell-output-display}\n![](rtp_exercises_files/figure-pdf/unnamed-chunk-15-2.pdf){fig-pos='H'}\n:::\n\n```{.r .cell-code}\ndecomp <- decompose(ts.stl.2$time.series[, \"trend\"], type = \"multiplicative\")\nacf(decomp$random, na.action = na.pass)\n```\n\n::: {.cell-output-display}\n![](rtp_exercises_files/figure-pdf/unnamed-chunk-15-3.pdf){fig-pos='H'}\n:::\n:::\n\n\n\n\n\n\n### D\n\n1. With `type = \"multiplicative\"` we assumes that seasonality is proportional to the trend.\n2. We used `stl(log(ts), ...)` because the original time series had an exponential trend.\n\n### E\n\n\n\n\n\n\n::: {.cell}\n\n```{.r .cell-code}\ncbe <- read.table(\"/home/nils/dev/mscids-notes/fs26/rtp/data/cbe.dat\", header = TRUE)\nts <- ts(cbe$elec,  start = c(1958, 1), frequency = 12)\n\nts.2 <- diff(ts, lag=1)\nplot(ts.2)\n```\n\n::: {.cell-output-display}\n![](rtp_exercises_files/figure-pdf/unnamed-chunk-16-1.pdf){fig-pos='H'}\n:::\n:::\n\n::: {.cell}\n\n```{.r .cell-code}\ncbe <- read.table(\"/home/nils/dev/mscids-notes/fs26/rtp/data/cbe.dat\", header = TRUE)\nts <- ts(cbe$elec,  start = c(1958, 1), frequency = 12)\n\nts.3 <- diff(ts, lag=12)\nplot(ts.3)\n```\n\n::: {.cell-output-display}\n![](rtp_exercises_files/figure-pdf/unnamed-chunk-17-1.pdf){fig-pos='H'}\n:::\n:::\n\n\n\n\n\n\nUsing differencing alone, we eliminate the trend but do not obtain a fully stationary time series.\n\n# Series 4\n\n## Exercise 4.1\n\n### A\n\n\n\n\n\n\n::: {.cell}\n\n```{.r .cell-code}\narima.sim(list(ar = c(0.8)), n = 1000)\n```\n:::\n\n\n\n\n\n\n### B\n\n\n\n\n\n\n::: {.cell}\n\n```{.r .cell-code}\ntheo <- ARMAacf(ar = c(0.5, 0.2), lag.max = 100)\nsim_data <- arima.sim(model = list(ar = c(0.5, 0.2)), n = 500)\nplugin <- acf(sim_data, lag.max = 100, plot = FALSE)$acf\n\nplot(0:100, theo, type = \"l\")\nlines(0:100, plugin)\n```\n\n::: {.cell-output-display}\n![](rtp_exercises_files/figure-pdf/unnamed-chunk-19-1.pdf){fig-pos='H'}\n:::\n:::\n\n\n\n\n\n\n### C\n\n\n\n\n\n\n::: {.cell}\n\n```{.r .cell-code}\nplot(0:20, ARMAacf(ar = 0.8, lag.max = 20), type = \"h\")\n```\n\n::: {.cell-output-display}\n![](rtp_exercises_files/figure-pdf/unnamed-chunk-20-1.pdf){fig-pos='H'}\n:::\n:::\n\n\n\n\n\n\n### D\n\n\n\n\n\n\n::: {.cell}\n\n```{.r .cell-code}\ntheo_pacf <- ARMAacf(ar = c(0.5, 0.2), lag.max = 100, pacf = TRUE)\nsim_data <- arima.sim(model = list(ar = c(0.5, 0.2)), n = 500)\nestim_pacf <- pacf(sim_data, lag.max = 100, plot = FALSE)$acf\n\nplot(1:100, theo_pacf, type = \"h\", ylim = c(-0.1, 0.6))\nlines(1:100, estim_pacf, type = \"l\")\n```\n\n::: {.cell-output-display}\n![](rtp_exercises_files/figure-pdf/unnamed-chunk-21-1.pdf){fig-pos='H'}\n:::\n:::\n\n\n\n\n\n\n## Exercise 4.2\n\n\n\n\n\n\n::: {.cell}\n\n```{.r .cell-code}\ndata <- read.table(\"/home/nils/dev/mscids-notes/fs26/rtp/data/kreatin.dat\", header=TRUE)\n```\n:::\n\n\n\n\n\n\n### A\n\nThe Model should follow a **Random Walk**.\n\n### B\n\n\n\n\n\n\n::: {.cell}\n\n```{.r .cell-code}\nts <- ts(data$gehalt, start=c(1,1))\nplot(ts, main=\"Creatine Concentration of Human Muscular Tissue\")\n```\n\n::: {.cell-output-display}\n![](rtp_exercises_files/figure-pdf/unnamed-chunk-23-1.pdf){fig-pos='H'}\n:::\n:::\n\n::: {.cell}\n\n```{.r .cell-code}\nacf(ts)\n```\n\n::: {.cell-output-display}\n![](rtp_exercises_files/figure-pdf/unnamed-chunk-24-1.pdf){fig-pos='H'}\n:::\n:::\n\n::: {.cell}\n\n```{.r .cell-code}\npacf(ts)\n```\n\n::: {.cell-output-display}\n![](rtp_exercises_files/figure-pdf/unnamed-chunk-25-1.pdf){fig-pos='H'}\n:::\n:::\n\n\n\n\n\n\n## Exercise 4.3\n\n\n\n\n\n\n::: {.cell}\n\n```{.r .cell-code}\ndata <- read.table(\"/home/nils/dev/mscids-notes/fs26/rtp/data/ts_S3_A2.dat\", header=TRUE)\n```\n:::\n\n\n\n\n\n\n### A\n\n\n\n\n\n\n::: {.cell}\n\n```{.r .cell-code}\nplot(ts(data$ts1))\nabline(h=mean(data$ts1))\n```\n\n::: {.cell-output-display}\n![](rtp_exercises_files/figure-pdf/unnamed-chunk-27-1.pdf){fig-pos='H'}\n:::\n:::\n\n\n\n\n\n\n$ts1$ seems to be stationary.\n\n\n\n\n\n\n::: {.cell}\n\n```{.r .cell-code}\nplot(ts(data$ts2))\nabline(h=mean(data$ts2))\n```\n\n::: {.cell-output-display}\n![](rtp_exercises_files/figure-pdf/unnamed-chunk-28-1.pdf){fig-pos='H'}\n:::\n:::\n\n\n\n\n\n\n$ts2$ seems not to be stationary.\n\n### B\n\n\n\n\n\n\n::: {.cell}\n\n```{.r .cell-code}\nacf(data$ts1)\n```\n\n::: {.cell-output-display}\n![](rtp_exercises_files/figure-pdf/unnamed-chunk-29-1.pdf){fig-pos='H'}\n:::\n\n```{.r .cell-code}\npacf(data$ts1)\n```\n\n::: {.cell-output-display}\n![](rtp_exercises_files/figure-pdf/unnamed-chunk-29-2.pdf){fig-pos='H'}\n:::\n:::\n\n\n\n\n\n\nThe time serie 1 seems to be a $ACF(1)$-process.\n\n\n\n\n\n\n::: {.cell}\n\n```{.r .cell-code}\nacf(data$ts2)\n```\n\n::: {.cell-output-display}\n![](rtp_exercises_files/figure-pdf/unnamed-chunk-30-1.pdf){fig-pos='H'}\n:::\n\n```{.r .cell-code}\npacf(data$ts2)\n```\n\n::: {.cell-output-display}\n![](rtp_exercises_files/figure-pdf/unnamed-chunk-30-2.pdf){fig-pos='H'}\n:::\n:::\n\n\n\n\n\n\nThe time serie 1 seems to be a $ACF(2)$-process.\n\n# Series 5\n\n## Task 5.1\n\n### A\n\n#### I\n\nThe ACF plot should have a drop at lag 3.\n\n#### II\n\n\n\n\n\n\n::: {.cell}\n\n```{.r .cell-code}\nplot(\n    0:30,\n    ARMAacf(\n        ar = c(0.9, -0.5),\n        lag.max = 30\n    ),\n    type = \"h\",\n    ylab = \"ACF\"\n)\n```\n\n::: {.cell-output-display}\n![](rtp_exercises_files/figure-pdf/unnamed-chunk-31-1.pdf){fig-pos='H'}\n:::\n:::\n\n::: {.cell}\n\n```{.r .cell-code}\nplot(\n    1:30,\n    ARMAacf(\n        ar = c(0.9, -0.5),\n        lag.max = 30,\n        pacf = TRUE\n    ),\n    type = \"h\",\n    ylab = \"PACF\"\n\n)\n```\n\n::: {.cell-output-display}\n![](rtp_exercises_files/figure-pdf/unnamed-chunk-32-1.pdf){fig-pos='H'}\n:::\n:::\n\n\n\n\n\n\n#### III\n\n\n\n\n\n\n::: {.cell}\n\n```{.r .cell-code}\nr.sim1 <- arima.sim(\n    n = 200,\n    model = list(ar = c(0.9, -0.5))\n)\n```\n:::\n\n\n\n\n\n\n#### IV\n\n\n\n\n\n\n::: {.cell}\n\n```{.r .cell-code}\nts.1 <- ts(r.sim1)\nplot(ts.1)\n```\n\n::: {.cell-output-display}\n![](rtp_exercises_files/figure-pdf/unnamed-chunk-34-1.pdf){fig-pos='H'}\n:::\n:::\n\n::: {.cell}\n\n```{.r .cell-code}\nacf(ts.1)\n```\n\n::: {.cell-output-display}\n![](rtp_exercises_files/figure-pdf/unnamed-chunk-35-1.pdf){fig-pos='H'}\n:::\n:::\n\n::: {.cell}\n\n```{.r .cell-code}\npacf(ts.1)\n```\n\n::: {.cell-output-display}\n![](rtp_exercises_files/figure-pdf/unnamed-chunk-36-1.pdf){fig-pos='H'}\n:::\n:::\n\n\n\n\n\n\n### B\n\n#### I\n\nThe PACF plot should have a drop at lag 4.\n\n#### II\n\n\n\n\n\n\n::: {.cell}\n\n```{.r .cell-code}\nplot(\n    0:30,\n    ARMAacf(\n        ar = c(0.8, -0.5, -0.4),\n        lag.max = 30\n    ),\n    type = \"h\",\n    ylab = \"ACF\"\n)\n```\n\n::: {.cell-output-display}\n![](rtp_exercises_files/figure-pdf/unnamed-chunk-37-1.pdf){fig-pos='H'}\n:::\n:::\n\n::: {.cell}\n\n```{.r .cell-code}\nplot(\n    1:30,\n    ARMAacf(\n        ar = c(0.8, -0.5, -0.4),\n        lag.max = 30,\n        pacf = TRUE\n    ),\n    type = \"h\",\n    ylab = \"PACF\"\n\n)\n```\n\n::: {.cell-output-display}\n![](rtp_exercises_files/figure-pdf/unnamed-chunk-38-1.pdf){fig-pos='H'}\n:::\n:::\n\n\n\n\n\n\n#### III\n\n\n\n\n\n\n::: {.cell}\n\n```{.r .cell-code}\nr.sim1 <- arima.sim(\n    n = 200,\n    model = list(ar = c(0.8, -0.5, -0.4))\n)\n```\n:::\n\n\n\n\n\n\n#### IV\n\n\n\n\n\n\n::: {.cell}\n\n```{.r .cell-code}\nts.1 <- ts(r.sim1)\nplot(ts.1)\n```\n\n::: {.cell-output-display}\n![](rtp_exercises_files/figure-pdf/unnamed-chunk-40-1.pdf){fig-pos='H'}\n:::\n:::\n\n::: {.cell}\n\n```{.r .cell-code}\nacf(ts.1)\n```\n\n::: {.cell-output-display}\n![](rtp_exercises_files/figure-pdf/unnamed-chunk-41-1.pdf){fig-pos='H'}\n:::\n:::\n\n::: {.cell}\n\n```{.r .cell-code}\npacf(ts.1)\n```\n\n::: {.cell-output-display}\n![](rtp_exercises_files/figure-pdf/unnamed-chunk-42-1.pdf){fig-pos='H'}\n:::\n:::\n\n\n\n\n\n\n## Exercise 5.2\n\n### A\n\n#### I\n\n\n\n\n\n\n::: {.cell}\n\n```{.r .cell-code}\nroots_i <- polyroot(c(1, -0.5, -2))\nabs(roots_i)\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n[1] 0.5930703 0.8430703\n```\n\n\n:::\n:::\n\n\n\n\n\n\nThe process is not stationary.\n\n#### II\n\n\n\n\n\n\n::: {.cell}\n\n```{.r .cell-code}\nroots_ii <- polyroot(c(1, -1))\nabs(roots_ii)\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n[1] 1\n```\n\n\n:::\n:::\n\n\n\n\n\n\nThe process is not stationary.\n\n### B\n\n$$\n0.5 + x = 1\n$$\n\n$$\nx = 1 - 0.5\n$$\n\n$$\nx = 0.5\n$$\n\nThe process is stationary for $\\alpha_2 = 0.5$.\n\n### C\n\nThe condition for stationarity is $∣\\alpha∣<1$. Therefore, if $∣\\alpha∣≥1$, the root $z=\\dfrac{1}{\\alpha}$​ lies either on the unit circle $(∣z∣=1)$ or inside it $(∣z∣≤1)$. This mathematically confirms that the model is non-stationary in these cases.\n\n# Series 6\n\n## Exercise 6.1\n\n\n\n\n\n\n::: {.cell}\n\n```{.r .cell-code}\nyields <- read.table(\"http://stat.ethz.ch/Teaching/Datasets/WBL/yields.dat\", header = FALSE)\n\nt.yields <- ts(yields[, 1])\n```\n:::\n\n\n\n\n\n\n### A\n\n\n\n\n\n\n::: {.cell}\n\n```{.r .cell-code}\nacf(t.yields)\n```\n\n::: {.cell-output-display}\n![](rtp_exercises_files/figure-pdf/unnamed-chunk-46-1.pdf){fig-pos='H'}\n:::\n:::\n\n::: {.cell}\n\n```{.r .cell-code}\npacf(t.yields)\n```\n\n::: {.cell-output-display}\n![](rtp_exercises_files/figure-pdf/unnamed-chunk-47-1.pdf){fig-pos='H'}\n:::\n:::\n\n\n\n\n\n\nThe process could be modelled by a $AR(p)$-Model with the value $p = 3$\n\n### B\n\n\n\n\n\n\n::: {.cell}\n\n```{.r .cell-code}\nr.yw <- ar(t.yields, method = \"yw\", order.max = 3)\nr.yw$resid\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\nTime Series:\nStart = 1 \nEnd = 70 \nFrequency = 1 \n [1]          NA          NA -23.2701676   8.5624227  -1.7185396   5.1017154\n [7]  10.3471780 -11.2034906   3.9364420   1.2089867  17.4563283  -9.2111662\n[13]  -2.8577303  -6.3524133   2.2572167  -2.9311234  25.3567725  14.3859910\n[19] -18.0787717  17.6571812   9.7250352   1.7201979   0.7723057   7.4553688\n[25]  -3.0885436   2.3171776   1.8505361  -7.5446312 -27.8857718   0.6164494\n[31]   6.0842678  18.0959587  11.4294237  20.8583891   5.3106389   2.4003827\n[37]  -3.7281741  -0.3234123 -13.1089096  -2.4829289   0.5084360   2.3548536\n[43]  -4.3282096   3.2157029   1.8505361   9.4553688  -3.4489132   8.6379522\n[49]  -2.7310524  -4.0412731 -11.3891299   3.5161116   8.7481019 -10.3049653\n[55]  -2.0635580   0.2900955 -18.1456261 -21.2240340   0.7913572  -2.3118589\n[61]  14.3954080  -6.6314966  -8.3591694  10.8697651  -9.0885436   2.3982863\n[67]  -6.4316031   0.8978066   6.7490614 -28.2653704\n```\n\n\n:::\n\n```{.r .cell-code}\nstr(r.yw)\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\nList of 15\n $ order       : int 2\n $ ar          : num [1:2] -0.32 0.18\n $ var.pred    : num 120\n $ x.mean      : num 51.1\n $ aic         : Named num [1:4] 9.84 0.298 0 2\n  ..- attr(*, \"names\")= chr [1:4] \"0\" \"1\" \"2\" \"3\"\n $ n.used      : int 70\n $ n.obs       : int 70\n $ order.max   : num 3\n $ partialacf  : num [1:3, 1, 1] -0.38988 0.17971 0.00226\n $ resid       : Time-Series [1:70] from 1 to 70: NA NA -23.27 8.56 -1.72 ...\n $ method      : chr \"Yule-Walker\"\n $ series      : chr \"t.yields\"\n $ frequency   : num 1\n $ call        : language ar(x = t.yields, order.max = 3, method = \"yw\")\n $ asy.var.coef: num [1:2, 1:2] 0.01444 0.00563 0.00563 0.01444\n - attr(*, \"class\")= chr \"ar\"\n```\n\n\n:::\n:::\n\n\n\n\n\n\nYule-Walker-Koeffizienten:\n\n* $\\alpha_1 = -0.32$\n* $\\alpha_2 = 0.18$\n\nModel:\n\n$$\nX_t = -0.32 \\cdot X_{t-1} + 0.18 \\cdot X_{t-2} + \\varepsilon_t\n$$\n\n### C\n\n\n\n\n\n\n::: {.cell}\n\n```{.r .cell-code}\nr.burg <- ar(t.yields, method = \"burg\", order.max = 3)\nr.burg$resid\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\nTime Series:\nStart = 1 \nEnd = 70 \nFrequency = 1 \n [1]          NA          NA -23.0964972   8.1701783  -1.3785617   4.8728473\n [7]  10.5505765 -11.1978722   3.7977236   1.3403098  17.3914298  -8.9537665\n[13]  -3.1238980  -6.2261379   2.0994588  -2.8089304  25.2454443  14.7685021\n[19] -18.1260033  17.4687299  10.0560689   1.6430522   0.8457311   7.4219430\n[25]  -2.9745155   2.2116763   1.9437802  -7.5780570 -27.9582418   0.3118307\n[31]   6.2684408  18.0559266  11.6802172  20.8533189   5.5789133   2.3108038\n[37]  -3.6390123  -0.4223073 -13.0529651  -2.6805103   0.5941087   2.3064707\n[43]  -4.2697412   3.1267173   1.9437802   9.4219430  -3.3100186   8.5134115\n[49]  -2.5474727  -4.1848533 -11.3514455   3.3500029   8.8893344 -10.2828313\n[55]  -2.2022764   0.3468193 -18.1782727 -21.4299662   0.6474050  -2.2228832\n[61]  14.3097254  -6.4014872  -8.5781282  10.8990986  -8.9745155   2.2181858\n[67]  -6.2936738   0.7334424   6.8588212 -28.2490633\n```\n\n\n:::\n\n```{.r .cell-code}\nstr(r.burg)\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\nList of 15\n $ order       : int 2\n $ ar          : num [1:2] -0.332 0.183\n $ var.pred    : num 113\n $ x.mean      : num 51.1\n $ aic         : Named num [1:4] 11.039 0.385 0 1.993\n  ..- attr(*, \"names\")= chr [1:4] \"0\" \"1\" \"2\" \"3\"\n $ n.used      : int 70\n $ n.obs       : int 70\n $ order.max   : num 3\n $ partialacf  : num [1:3, 1, 1] -0.4067 0.183 0.0103\n $ resid       : Time-Series [1:70] from 1 to 70: NA NA -23.1 8.17 -1.38 ...\n $ method      : chr \"Burg\"\n $ series      : chr \"t.yields\"\n $ frequency   : num 1\n $ call        : language ar(x = t.yields, order.max = 3, method = \"burg\")\n $ asy.var.coef: num [1:2, 1:2] 0.0136 0.0053 0.0053 0.0136\n - attr(*, \"class\")= chr \"ar\"\n```\n\n\n:::\n:::\n\n\n\n\n\n\nBurg-Koeffizienten:\n\n* $\\alpha_1 = -0.332$\n* $\\alpha_2 = 0.183$\n\nModel:\n\n$$\nX_t = -0.332 \\cdot X_{t-1} + 0.183 \\cdot X_{t-2} + \\varepsilon_t\n$$\n\n### D\n\n\n\n\n\n\n::: {.cell}\n\n```{.r .cell-code}\nr.mle <- ar(t.yields, method = \"mle\", order.max = 3)\nr.mle$resid\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\nTime Series:\nStart = 1 \nEnd = 70 \nFrequency = 1 \n [1]            NA            NA -23.083437837   7.762346509  -1.201980697\n [6]   4.561565507  10.602738000 -11.334850093   3.581349256   1.337116357\n[11]  17.216926017  -8.885802464  -3.460572312  -6.220191632   1.865930909\n[16]  -2.816243379  25.041428463  14.930022474 -18.332496024  17.218498832\n[21]  10.197216932   1.428770775   0.782162438   7.273056970  -3.008346873\n[26]   2.007435328   1.906279662  -7.726943030 -28.119035966   0.003476264\n[31]   6.334762287  17.898351229  11.739491795  20.694392418   5.637512389\n[36]   2.088058169  -3.689772086  -0.617858931 -13.115858157  -2.934860904\n[41]   0.570317679   2.153690370  -4.337204163   2.944199681   1.906279662\n[46]   9.273056970  -3.326921661   8.292016980  -2.521379225  -4.423401367\n[51] -11.422577628   3.121270050   8.899174969 -10.398085740  -2.418650744\n[56]   0.292840720 -18.318244153 -21.679521763   0.471483903  -2.242329450\n[61]  14.131552552  -6.345881671  -8.876375881  10.832761513  -9.008346873\n[66]   1.963159691  -6.288177902   0.491225167   6.843044015 -28.364092605\n```\n\n\n:::\n\n```{.r .cell-code}\nstr(r.mle)\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\nList of 15\n $ order       : int 2\n $ ar          : num [1:2] -0.341 0.187\n $ var.pred    : num 113\n $ x.mean      : num 51.2\n $ aic         : Named num [1:4] 10.808 0.301 0 1.969\n  ..- attr(*, \"names\")= chr [1:4] \"0\" \"1\" \"2\" \"3\"\n $ n.used      : int 70\n $ n.obs       : int 70\n $ order.max   : num 3\n $ partialacf  : NULL\n $ resid       : Time-Series [1:70] from 1 to 70: NA NA -23.08 7.76 -1.2 ...\n $ method      : chr \"MLE\"\n $ series      : chr \"t.yields\"\n $ frequency   : num 1\n $ call        : language ar(x = t.yields, order.max = 3, method = \"mle\")\n $ asy.var.coef: num [1:2, 1:2] 0.0136 0.0053 0.0053 0.0136\n - attr(*, \"class\")= chr \"ar\"\n```\n\n\n:::\n:::\n\n\n\n\n\n\n## Exercise 6.2\n\n\n\n\n\n\n::: {.cell}\n\n```{.r .cell-code}\nd.force <- read.table(\"http://stat.ethz.ch/Teaching/Datasets/WBL/kraft.dat\", header = FALSE)\nts.force <- ts(d.force[, 1])\n```\n:::\n\n\n\n\n\n\n### A\n\n\n\n\n\n\n::: {.cell}\n\n```{.r .cell-code}\nts.forceA <- window(ts.force, end = 280)\nplot(ts.forceA)\n```\n\n::: {.cell-output-display}\n![](rtp_exercises_files/figure-pdf/unnamed-chunk-52-1.pdf){fig-pos='H'}\n:::\n:::\n\n\n\n\n\n\n### B\n\n\n\n\n\n\n::: {.cell}\n\n```{.r .cell-code}\npacf(ts.forceA)\n```\n\n::: {.cell-output-display}\n![](rtp_exercises_files/figure-pdf/unnamed-chunk-53-1.pdf){fig-pos='H'}\n:::\n:::\n\n::: {.cell}\n\n```{.r .cell-code}\nar.force <- ar(ts.forceA, method = \"ols\", order = 6)\nar.force$aic\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n        0         1         2         3         4         5         6 \n661.05054 283.10981 180.20653 135.93284  80.06312  58.33776   0.00000 \n```\n\n\n:::\n:::\n\n\n\n\n\n\n### C\n\n\n\n\n\n\n::: {.cell}\n\n```{.r .cell-code}\nar.force <- arima(ts.forceA, order = c(6, 0, 0), method = \"ML\")\nplot(ar.force$res)\nabline(h=0, col=\"red\", lty=2)\n```\n\n::: {.cell-output-display}\n![](rtp_exercises_files/figure-pdf/unnamed-chunk-55-1.pdf){fig-pos='H'}\n:::\n:::\n\n\n\n\n\n\nThe model seems to be appropriate for this time series since the residuals looks normal distributed.\n\n# Series 7\n\n## Exercise 7.1\n\n### A\n\n\n\n\n\n\n::: {.cell}\n\n```{.r .cell-code}\narma.1 <-arima.sim(n=250,list(ar=c(-0.75),ma=c(-0.3, 0.25)))\n```\n:::\n\n\n\n\n\n\n### B\n\n\n\n\n\n\n::: {.cell}\n\n```{.r .cell-code}\narma.2 <-arima.sim(n=250,list(ar=c(-0.75, -0.3),ma=c(0.25)))\n```\n:::\n\n\n\n\n\n\n## Exercise 7.2\n\n\n\n\n\n\n::: {.cell}\n\n```{.r .cell-code}\nlibrary(fpp2)\ndata(sunspotarea)\nplot(sunspotarea)\n```\n\n::: {.cell-output-display}\n![](rtp_exercises_files/figure-pdf/unnamed-chunk-58-1.pdf){fig-pos='H'}\n:::\n:::\n\n\n\n\n\n\n### B\n\n\n\n\n\n\n::: {.cell}\n\n```{.r .cell-code}\nts.sunspotarea <- ts(log(sunspotarea))\nts.sunspotareaA <- window(ts.sunspotarea, end = 100)\n```\n:::\n\n::: {.cell}\n\n```{.r .cell-code}\nacf(ts.sunspotareaA)\n```\n\n::: {.cell-output-display}\n![](rtp_exercises_files/figure-pdf/unnamed-chunk-60-1.pdf){fig-pos='H'}\n:::\n:::\n\n::: {.cell}\n\n```{.r .cell-code}\npacf(ts.sunspotareaA)\n```\n\n::: {.cell-output-display}\n![](rtp_exercises_files/figure-pdf/unnamed-chunk-61-1.pdf){fig-pos='H'}\n:::\n:::\n\n\n\n\n\n\nBased on the $(p-)acf$, we choose a $AR$-model with the value $p = 3$\n\n## Exercise 7.3\n\n\n\n\n\n\n::: {.cell}\n\n```{.r .cell-code}\nt.url <- \"http://stat.ethz.ch/Teaching/Datasets/WBL/varve.dat\"\nd.varve <- ts(scan(t.url)[201:550])\n```\n:::\n\n\n\n\n\n\n### A\n\n\n\n\n\n\n::: {.cell}\n\n```{.r .cell-code}\nplot(d.varve)\n```\n\n::: {.cell-output-display}\n![](rtp_exercises_files/figure-pdf/unnamed-chunk-63-1.pdf){fig-pos='H'}\n:::\n:::\n\n\n\n\n\n\nYes, there is a need for log-transform.\n\n### B\n\n\n\n\n\n\n::: {.cell}\n\n```{.r .cell-code}\nplot(log(d.varve))\n```\n\n::: {.cell-output-display}\n![](rtp_exercises_files/figure-pdf/unnamed-chunk-64-1.pdf){fig-pos='H'}\n:::\n:::\n\n\n\n\n\n\nThe time series it not stationary by simply using log-tranformation. We try differencing.\n\n\n\n\n\n\n::: {.cell}\n\n```{.r .cell-code}\nplot(diff(d.varve, 10))\n```\n\n::: {.cell-output-display}\n![](rtp_exercises_files/figure-pdf/unnamed-chunk-65-1.pdf){fig-pos='H'}\n:::\n:::\n\n\n\n\n\n\nLooks good now.\n\n# Series 8\n\n## Exercise 8.1\n\n### A\n\n```r\narima.1 <-arima.sim(\n    n=250,\n    order=c(2, 1, 2),\n    list(\n        ar=c(0.5, 0,5),ma=c(-0.4, 0.3)\n        )\n    )\n```\n\nThe problem: `ar` part of model is not stationary!\n\n### B\n\n\n\n\n\n\n::: {.cell}\n\n```{.r .cell-code}\n# 1. Define the coefficients as polynomials: c(1, -coef1, -coef2)\nar_poly <- c(1, -0.5, -0.5) \ndiff_poly <- c(1, -1)       \n\n# 2. Multiply the polynomials using convolution\n# We reverse the second vector (diff_poly) because of how convolve() calculates\narma_ar_poly <- convolve(ar_poly, rev(diff_poly), type = \"open\")\n\n# View the resulting polynomial: 1 - 1.5*B + 0*B^2 + 0.5*B^3\nprint(arma_ar_poly) \n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n[1]  1.0 -1.5  0.0  0.5\n```\n\n\n:::\n\n```{.r .cell-code}\n# Output: [1]  1.0 -1.5  0.0  0.5\n\n# 3. Extract the ARMA coefficients\n# Drop the intercept (the first '1') and flip the signs back to standard AR format\narma_ar_coefs <- -arma_ar_poly[-1]\n\n# 4. The MA coefficients remain identical to the original ARIMA model\narma_ma_coefs <- c(-0.4, 0.3)\n\n# Print final coefficients\ncat(\"Equivalent ARMA AR coefficients:\", arma_ar_coefs, \"\\n\")\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\nEquivalent ARMA AR coefficients: 1.5 0 -0.5 \n```\n\n\n:::\n\n```{.r .cell-code}\ncat(\"Equivalent ARMA MA coefficients:\", arma_ma_coefs, \"\\n\")\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\nEquivalent ARMA MA coefficients: -0.4 0.3 \n```\n\n\n:::\n:::\n\n\n\n\n\n\n> Note: Solution generated by AI (Gemini 3.1 Pro).\n\n## Exercise 8.2\n\n\n\n\n\n\n::: {.cell}\n\n```{.r .cell-code}\nd.beluga <- read.table(\"http://stat.ethz.ch/Teaching/Datasets/WBL/beluga.dat\", header = TRUE)\nd.beluga <- ts(d.beluga)\n```\n:::\n\n\n\n\n\n\n### A\n\n\n\n\n\n\n::: {.cell}\n\n```{.r .cell-code}\ny = lm(NURSING ~ ., data=d.beluga)\ny\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n\nCall:\nlm(formula = NURSING ~ ., data = d.beluga)\n\nCoefficients:\n(Intercept)       PERIOD        BOUTS      LOCKONS     DAYNIGHT  \n  0.5602842    0.0001998    0.8784967    2.3903512   -0.3416237  \n```\n\n\n:::\n:::\n\n::: {.cell}\n\n```{.r .cell-code}\nplot(y$res, type=\"l\")\nabline(h=0, col=\"red\")\n```\n\n::: {.cell-output-display}\n![](rtp_exercises_files/figure-pdf/unnamed-chunk-69-1.pdf){fig-pos='H'}\n:::\n:::\n\n\n\n\n\n\n### B\n\n``` r\nacf(d.beluga)\n```\n\n\n\n\n\n\n::: {.cell}\n\n```{.r .cell-code}\nr.burg <- ar(\n    x=d.beluga,\n    order.max=8\n    )\nplot(r.burg$res)\n```\n\n::: {.cell-output-display}\n![](rtp_exercises_files/figure-pdf/unnamed-chunk-70-1.pdf){fig-pos='H'}\n:::\n:::\n\n\n\n\n\n\n### C\n\n\n\n\n\n\n::: {.cell}\n\n```{.r .cell-code}\nlibrary(nlme) # Load the package containing the procedure gls()\n\nr.bel.gls <- gls(\n    NURSING ~ BOUTS + LOCKONS + DAYNIGHT + PERIOD,\n    data = d.beluga,\n    correlation = corARMA(\n        form = ~PERIOD,\n        p = r.burg$order,\n        q = 0,\n        fixed = FALSE\n    ),\n    method = \"ML\"\n    )\n\nsummary(r.bel.gls)\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\nGeneralized least squares fit by maximum likelihood\n  Model: NURSING ~ BOUTS + LOCKONS + DAYNIGHT + PERIOD \n  Data: d.beluga \n       AIC      BIC    logLik\n  562.0881 589.7647 -272.0441\n\nCorrelation Structure: ARMA(3,0)\n Formula: ~PERIOD \n Parameter estimate(s):\n      Phi1       Phi2       Phi3 \n0.25683813 0.35339180 0.04517223 \n\nCoefficients:\n                 Value Std.Error   t-value p-value\n(Intercept)  1.2919742 0.7810844  1.654078  0.1001\nBOUTS        0.2794180 0.3358771  0.831906  0.4067\nLOCKONS      2.5827939 0.1966869 13.131499  0.0000\nDAYNIGHT    -0.3072369 0.1572643 -1.953634  0.0525\nPERIOD       0.0027855 0.0064980  0.428668  0.6688\n\n Correlation: \n         (Intr) BOUTS  LOCKON DAYNIG\nBOUTS    -0.291                     \nLOCKONS  -0.103 -0.811              \nDAYNIGHT -0.018 -0.132  0.066       \nPERIOD   -0.619 -0.228  0.241  0.023\n\nStandardized residuals:\n        Min          Q1         Med          Q3         Max \n-2.80574698 -0.59171135  0.01765555  0.65367271  2.49056057 \n\nResidual standard error: 1.576717 \nDegrees of freedom: 160 total; 155 residual\n```\n\n\n:::\n\n```{.r .cell-code}\nd.resid <- ts(resid(r.bel.gls))\n```\n:::\n\n\n\n\n\n\n## Exercise 8.3\n\n### A\n\n\n\n\n\n\n::: {.cell}\n\n```{.r .cell-code}\nt.url <- \"http://stat.ethz.ch/Teaching/Datasets/WBL/varve.dat\"\nd.varve <- ts(scan(t.url)[201:550])\n```\n:::\n\n::: {.cell}\n\n```{.r .cell-code}\nacf(diff(log(d.varve)))\n```\n\n::: {.cell-output-display}\n![](rtp_exercises_files/figure-pdf/unnamed-chunk-73-1.pdf){fig-pos='H'}\n:::\n:::\n\n::: {.cell}\n\n```{.r .cell-code}\npacf(log(d.varve))\n```\n\n::: {.cell-output-display}\n![](rtp_exercises_files/figure-pdf/unnamed-chunk-74-1.pdf){fig-pos='H'}\n:::\n:::\n\n::: {.cell}\n\n```{.r .cell-code}\nr.varve <- arima(\n    x=log(d.varve),\n    order = c(2, 1, 2),\n    method=\"ML\"\n    )\nr.varve\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n\nCall:\narima(x = log(d.varve), order = c(2, 1, 2), method = \"ML\")\n\nCoefficients:\n          ar1     ar2      ma1      ma2\n      -0.1442  0.1452  -0.5334  -0.3548\ns.e.   0.5439  0.1345   0.5453   0.4968\n\nsigma^2 estimated as 0.2132:  log likelihood = -226.21,  aic = 462.42\n```\n\n\n:::\n:::\n\n\n\n\n\n\n### B\n\n$$\ny = -0.1442\\alpha_1 + 0.1452\\alpha_2 + -0.5334\\beta_1 + -0.3548\\beta_2 + \\varepsilon_0\n$$\n\n# Series 9\n\n## Exercise 9.1\n\n### A\n\n\n\n\n\n\n\n::: {.cell}\n\n```{.r .cell-code}\nlibrary(astsa)\ndata(prodn)\n\nplot(prodn)\n```\n\n::: {.cell-output-display}\n![](rtp_exercises_files/figure-pdf/unnamed-chunk-76-1.pdf){fig-pos='H'}\n:::\n:::\n\n\n\n\n\n\n### B\n\n\n\n\n\n\n::: {.cell}\n\n```{.r .cell-code}\nplot(diff(log(prodn)))\n```\n\n::: {.cell-output-display}\n![](rtp_exercises_files/figure-pdf/unnamed-chunk-77-1.pdf){fig-pos='H'}\n:::\n:::\n\n\n\n\n\n\n### C\n\n\n\n\n\n\n::: {.cell}\n\n```{.r .cell-code}\nprodn.trans <- diff(log(prodn))\n\nacf(prodn.trans)\n```\n\n::: {.cell-output-display}\n![](rtp_exercises_files/figure-pdf/unnamed-chunk-78-1.pdf){fig-pos='H'}\n:::\n:::\n\n::: {.cell}\n\n```{.r .cell-code}\npacf(prodn.trans)\n```\n\n::: {.cell-output-display}\n![](rtp_exercises_files/figure-pdf/unnamed-chunk-79-1.pdf){fig-pos='H'}\n:::\n:::\n\n::: {.cell}\n\n```{.r .cell-code}\nlibrary(forecast)\n\nfit<-arima(\n    x=prodn.trans,\n    order=c(1,1,1),\n    seasonal=c(1,1,1)\n    )\n\ntsdisplay(fit$residual)\n```\n\n::: {.cell-output-display}\n![](rtp_exercises_files/figure-pdf/unnamed-chunk-80-1.pdf){fig-pos='H'}\n:::\n:::\n\n::: {.cell}\n\n```{.r .cell-code}\nfitAuto<-auto.arima(prodn.trans, ic=\"aic\")\nfitAuto\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\nSeries: prodn.trans \nARIMA(3,0,0)(2,1,1)[12] \n\nCoefficients:\n         ar1     ar2      ar3     sar1    sar2     sma1\n      0.2431  0.1458  -0.0493  -0.1832  -0.240  -0.6940\ns.e.  0.0527  0.0544   0.0531   0.0708   0.063   0.0583\n\nsigma^2 = 0.0002249:  log likelihood = 993.91\nAIC=-1973.83   AICc=-1973.51   BIC=-1946.65\n```\n\n\n:::\n\n```{.r .cell-code}\ntsdisplay(fitAuto$residual)\n```\n\n::: {.cell-output-display}\n![](rtp_exercises_files/figure-pdf/unnamed-chunk-81-1.pdf){fig-pos='H'}\n:::\n:::\n\n\n\n\n\n\n# Series 10\n\n## Exercise 10.1\n\n\n\n\n\n\n::: {.cell}\n\n```{.r .cell-code}\nlibrary(fpp2)\n\nlsunspot100 <- window(log(sunspotarea), start = 1875, end = 1974)\nfit.ar10 <- arima(lsunspot100, order = c(10, 0, 0))\nfit.ar10\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n\nCall:\narima(x = lsunspot100, order = c(10, 0, 0))\n\nCoefficients:\n         ar1      ar2     ar3      ar4     ar5      ar6     ar7      ar8\n      0.7171  -0.1887  0.0045  -0.0621  0.0220  -0.1140  0.1694  -0.2284\ns.e.  0.0938   0.1175  0.1176   0.1180  0.1159   0.1183  0.1184   0.1189\n         ar9    ar10  intercept\n      0.1272  0.3601     6.1045\ns.e.  0.1207  0.0970     0.2597\n\nsigma^2 estimated as 0.3439:  log likelihood = -91.1,  aic = 206.2\n```\n\n\n:::\n:::\n\n\n\n\n\n\n### A\n\n\n\n\n\n\n::: {.cell}\n\n```{.r .cell-code}\npred <- predict(fit.ar10, n.ahead = 100)\n\nplot(x=lsunspot100, xlim = c(1875, 2074))\nabline(h = fit.ar10$coef[\"intercept\"], lty = 2)\nlines(pred$pred, col = \"green\")\n```\n\n::: {.cell-output-display}\n![](rtp_exercises_files/figure-pdf/unnamed-chunk-83-1.pdf){fig-pos='H'}\n:::\n:::\n\n\n\n\n\n\n### B\n\n\n\n\n\n\n::: {.cell}\n\n```{.r .cell-code}\npred_b <- predict(fit.ar10, n.ahead = 37)\n\nplot(lsunspot100, \n     main = \"Log-Transformed Sunspot Area with AR(10) Predictions\",\n     ylab = \"Log(Area)\", \n     xlab = \"Year\",\n     xlim = c(1875, 2015))\nlines(pred_b$pred, col = \"blue\", lwd = 2)\nlines(pred_b$pred + 1.96 * pred_b$se, col = \"red\", lty = 2)\nlines(pred_b$pred - 1.96 * pred_b$se, col = \"red\", lty = 2)\n```\n\n::: {.cell-output-display}\n![](rtp_exercises_files/figure-pdf/unnamed-chunk-84-1.pdf){fig-pos='H'}\n:::\n\n```{.r .cell-code}\n# 6. Calculate the Mean Squared Forecasting Error (MSFE)\n# Extract the actual observed values for the out-of-sample period (1975-2011)\nactual_out_of_sample <- window(sunspotarea, start = 1975, end = 2011)\n\n# Compute the Mean Squared Error between actuals and predictions\nmsfe <- mean((actual_out_of_sample - pred_b$pred)^2)\n\ncat(\"Mean Squared Forecasting Error (MSFE):\", msfe, \"\\n\")\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\nMean Squared Forecasting Error (MSFE): 1562725 \n```\n\n\n:::\n:::\n\n\n\n\n\n\n> Note: Solution generated by AI (Gemeni 3.1 Pro).\n\n## Exercise 10.2\n\n\n\n\n\n\n::: {.cell}\n\n```{.r .cell-code}\ndata(\"AirPassengers\")\nd.air <- AirPassengers\nd.airshort <- window(d.air, end = c(1956, 12))\nplot(d.airshort)\n```\n\n::: {.cell-output-display}\n![](rtp_exercises_files/figure-pdf/unnamed-chunk-85-1.pdf){fig-pos='H'}\n:::\n:::\n\n\n\n\n\n\n### A\n\n\n\n\n\n\n::: {.cell}\n\n```{.r .cell-code}\nd.airshort.trans <- diff(log(d.airshort))\nfit <- auto.arima(d.airshort.trans, ic=\"aic\")\n\n#Perform forecast\nfc <- predict(fit, n.ahead=4*12)\n\n#Plot everything\nplot(\n    x=d.airshort.trans,\n    lty=3,\n    xlim=c(1957,1960)\n    )\nlines(d.airshort, lwd=1)\nlines(fc$pred, lwd=2, col=\"red\")\nlines(fc$pred+fc$se*1.96, col=\"blue\")\nlines(fc$pred-fc$se*1.96, col=\"blue\")\n```\n\n::: {.cell-output-display}\n![](rtp_exercises_files/figure-pdf/unnamed-chunk-86-1.pdf){fig-pos='H'}\n:::\n:::\n\n\n\n\n\n\n# Series 11\n\n## Exercise 11.1\n\n### A\n\n| Process | Simplified Formula | Mean | Variance | Stationary? | Time-Series Classification |\n| :--- | :--- | :--- | :--- | :--- | :--- |\n| **i) $X_t$** | $t + E_t$ | $t$ *(Changes with time)* | $\\sigma^2$ *(Constant)* | **No** | Trend-Stationary (Raw process is non-stationary) |\n| **ii) $Y_t$** | $1 + E_t - E_{t-1}$ | $1$ *(Constant)* | $2\\sigma^2$ *(Constant)* | **Yes** | Stationary MA(1) process with a drift |\n| **iii) $Z_t$** | $E_t$ | $0$ *(Constant)* | $\\sigma^2$ *(Constant)* | **Yes** | Stationary White Noise |\n\n### C\n\n\n\n\n\n\n::: {.cell}\n\n```{.r .cell-code}\nt.E <- ts(rnorm(201))\nt.X <- (1:201) + t.E\nt.Y <- diff(t.X)\nt.Z <- t.E\n```\n:::\n\n::: {.cell}\n\n```{.r .cell-code}\nplot(t.Y)\n```\n\n::: {.cell-output-display}\n![](rtp_exercises_files/figure-pdf/unnamed-chunk-88-1.pdf){fig-pos='H'}\n:::\n:::\n\n::: {.cell}\n\n```{.r .cell-code}\nplot(t.Z)\n```\n\n::: {.cell-output-display}\n![](rtp_exercises_files/figure-pdf/unnamed-chunk-89-1.pdf){fig-pos='H'}\n:::\n:::\n\n\n\n\n\n\n# Series 12\n\n## Exercise 12.1\n\n\n\n\n\n\n::: {.cell}\n\n```{.r .cell-code}\nlibrary(AER)\ndata(\"Guns\")\n```\n:::\n\n\n\n\n\n\n### A\n\n#### I\n\n\n\n\n\n\n::: {.cell}\n\n```{.r .cell-code}\nsummary(\"Guns\")\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n   Length  N.unique   N.blank Min.nchar Max.nchar \n        1         1         0         4         4 \n```\n\n\n:::\n:::\n\n\n\n\n\n\n#### II\n\n\n\n\n\n\n::: {.cell}\n\n```{.r .cell-code}\n# verify that panel is balanced\nyears <- length(levels(Guns$year))\nstates <- length(levels(Guns$state))\nyears * states == nrow(Guns)\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n[1] TRUE\n```\n\n\n:::\n:::\n\n\n\n\n\n\nThe dataset is balanced!\n\n### B\n\n#### I\n\n\n\n\n\n\n::: {.cell}\n\n```{.r .cell-code}\nlibrary(plm)\n\nmodel.se <- plm(\n    formula = log(violent) ~ law,\n    data = Guns,\n    index = c(\"state\", \"year\"),\n    model = \"within\"\n    )\n\nmodel.se\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n\nModel Formula: log(violent) ~ law\n\nCoefficients:\n lawyes \n0.11366 \n```\n\n\n:::\n:::\n\n\n\n\n\n\n#### II\n\n\n\n\n\n\n::: {.cell}\n\n```{.r .cell-code}\ncoeftest(model.se, vcov. = vcovHC, type = \"HC1\")\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n\nt test of coefficients:\n\n       Estimate Std. Error t value Pr(>|t|)   \nlawyes 0.113663   0.035689  3.1848 0.001488 **\n---\nSignif. codes:  0 '***' 0.001 '**' 0.01 '*' 0.05 '.' 0.1 ' ' 1\n```\n\n\n:::\n:::\n\n\n\n\n\n\n#### III\n\n\n\n\n\n\n::: {.cell}\n\n```{.r .cell-code}\nmodel = plm(log(violent) ~ law, data = Guns, index = c(\"state\", \"year\"), model = \"pooling\")\n\npFtest(model.se, model)\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n\n\tF test for individual effects\n\ndata:  log(violent) ~ law\nF = 260.5, df1 = 50, df2 = 1121, p-value < 2.2e-16\nalternative hypothesis: significant effects\n```\n\n\n:::\n:::\n",
    "supporting": [
      "rtp_exercises_files/figure-pdf"
    ],
    "filters": [
      "rmarkdown/pagebreak.lua"
    ],
    "includes": {},
    "engineDependencies": {},
    "preserve": null,
    "postProcess": false
  }
}