{
  "hash": "da7646cfc20b45eb918af49f95097414",
  "result": {
    "engine": "knitr",
    "markdown": "---\ntitle: Applied Machine Learning and Predictive Modelling 1 - Exercises\nauthor: Nils Rechberger\ndate: 2026-02-21\n---\n\n\n\n\n\n\n# Series 1: Linear Models\n\nIn class we fitted a model to the “cats” dataset. You may remember that the interpretation of the intercept was somehow problematic. Let’s get the data, visualise it and refit the model again.\n\n\n\n\n\n\n::: {.cell}\n\n```{.r .cell-code}\nd.cats <- read.csv(\n    file = \"/home/nils/dev/mscids-notes/fs26/mpm1/data/Cats.csv\",\n    header = TRUE,\n    stringsAsFactors = TRUE\n    )\n\nstr(d.cats)\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n'data.frame':\t144 obs. of  3 variables:\n $ Sex         : Factor w/ 2 levels \"F\",\"M\": 1 1 1 1 1 1 1 1 1 1 ...\n $ Body.weight : num  2 2 2 2.1 2.1 2.1 2.1 2.1 2.1 2.1 ...\n $ Heart.weight: num  7 7.4 9.5 7.2 7.3 7.6 8.1 8.2 8.3 8.5 ...\n```\n\n\n:::\n\n```{.r .cell-code}\nhead(d.cats)\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n  Sex Body.weight Heart.weight\n1   F         2.0          7.0\n2   F         2.0          7.4\n3   F         2.0          9.5\n4   F         2.1          7.2\n5   F         2.1          7.3\n6   F         2.1          7.6\n```\n\n\n:::\n:::\n\n\n\n\n\n\nLet’s display the effect of Body.weight.\n\n\n\n\n\n\n::: {.cell}\n\n```{.r .cell-code}\nplot(Heart.weight ~ Body.weight, data = d.cats)\n```\n\n::: {.cell-output-display}\n![](mpm1_exercises_files/figure-pdf/unnamed-chunk-2-1.pdf){fig-pos='H'}\n:::\n:::\n\n\n\n\n\n\nThe first model we fitted was:\n\n\n\n\n\n\n::: {.cell}\n\n```{.r .cell-code}\nlm.cats <- lm(Heart.weight ~ Body.weight, data = d.cats)\n```\n:::\n\n\n\n\n\n\nThe estimated coefficients of this model are:\n\n\n\n\n\n\n::: {.cell}\n\n```{.r .cell-code}\ncoef(lm.cats)\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n(Intercept) Body.weight \n -0.3566624   4.0340627 \n```\n\n\n:::\n:::\n\n\n\n\n\n\nAs mentioned in class, the correct interpretation of the intercept is “a cat with zero body.weight, is expected to have a heart weight of -0.36”. It is obviously nonsensical for two reasons:\n\n1. There is no cat of zero body weight\n2. A negative prediction for the response variable heart.weight is impossible in reality.\n\n## Questions\n\n### Question 1\n\nHow would you proceed to simplify the interpretation of the intercept in this model? Hint: try to manipulate the predictor body.weight (e.g. by centering it).\n\n#### Answer\n\nBy centering the variable `Body.weight`, we can get a interpretable intercept.\n\n$$\n\\text{Body.weight.cent} = \\text{Body.weight} - \\bar{x}\n$$\n\n\n\n\n\n\n::: {.cell}\n\n```{.r .cell-code}\nd.cats$Body.weight.cent <- d.cats$Body.weight - mean(d.cats$Body.weight)\nplot(Heart.weight ~ Body.weight.cent, data = d.cats)\n```\n\n::: {.cell-output-display}\n![](mpm1_exercises_files/figure-pdf/unnamed-chunk-5-1.pdf){fig-pos='H'}\n:::\n:::\n\n\n\n\n\n\n### Question 2\n\nLet’s turn our attention to the model that contains sex too, but no interaction. Reparametrise this model such that \"M\" is the reference. Hint: use the relevel() function.\n\n#### Answer\n\nFirst we check the current level of `Sex`.\n\n\n\n\n\n\n::: {.cell}\n\n```{.r .cell-code}\nlevels(d.cats$Sex)\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n[1] \"F\" \"M\"\n```\n\n\n:::\n:::\n\n\n\n\n\n\nWe can see that `F` ist the reference level. To change that:\n\n\n\n\n\n\n::: {.cell}\n\n```{.r .cell-code}\nd.cats$Sex <- relevel(x = d.cats$Sex, ref = \"M\")\nlevels(d.cats$Sex)\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n[1] \"M\" \"F\"\n```\n\n\n:::\n:::\n\n\n\n\n\n\nNow we need to refit our model:\n\n\n\n\n\n\n::: {.cell}\n\n```{.r .cell-code}\nlm.cats.relevelled <- lm(Heart.weight ~ Body.weight + Sex, data = d.cats)\ncoef(lm.cats.relevelled)\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n(Intercept) Body.weight        SexF \n-0.49704946  4.07576892  0.08209684 \n```\n\n\n:::\n:::\n\n\n\n\n\n\n### Question 3\n\nWhen the predictor sex was added to the model, the estimated coefficient for ‘body.weight‘ slightly changed. Refit both models, show the estimated coefficients and write a sentence that correctly describes their \"biological interpretation\" of the Body.weight predictor in each model.\n\n#### Answer\n\n\n\n\n\n\n::: {.cell}\n\n```{.r .cell-code}\ncat(\"Ceoff for without sex:\", coef(lm.cats), \"\\n\")\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\nCeoff for without sex: -0.3566624 4.034063 \n```\n\n\n:::\n\n```{.r .cell-code}\ncat(\"Ceoff for with sex:\", coef(lm.cats.relevelled))\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\nCeoff for with sex: -0.4970495 4.075769 0.08209684\n```\n\n\n:::\n:::\n\n\n\n\n\n\n- First model: By increasing by one unit body weight, we expect an increase of 4.03 in the response variable.\n- Second model: By increasing by one unit body weight, while keeping all the other predictors fixed, we expect an increase of 4.08 in the response\nvariable.\n\n### Question 4\n\nThis time we assume that Body.weight was not provided as a continuous variable, but rather as a categorical one. We do this by creating four classes with similar size. With this purpose in mind, we use the `quantil()` and `cut()` functions.\n\n\n\n\n\n\n::: {.cell}\n\n```{.r .cell-code}\nquantiles.Body.weight <- quantile(d.cats$Body.weight)\nquantiles.Body.weight\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n   0%   25%   50%   75%  100% \n2.000 2.300 2.700 3.025 3.900 \n```\n\n\n:::\n\n```{.r .cell-code}\nd.cats$Body.weight.Class <- cut(\n    x = d.cats$Body.weight,\n    breaks = quantiles.Body.weight,\n    include.lowest = TRUE\n    )\n```\n:::\n\n\n\n\n\n\nLet’s check how many observations are present in each class.\n\n\n\n\n\n\n::: {.cell}\n\n```{.r .cell-code}\ntable(d.cats$Body.weight.Class)\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n\n   [2,2.3]  (2.3,2.7] (2.7,3.02] (3.02,3.9] \n        42         40         26         36 \n```\n\n\n:::\n:::\n\n\n\n\n\n\nFit a model with Sex and Body.weight.Class and compute a p-value for both predictors.\n\n#### Answer\n\n\n\n\n\n\n::: {.cell}\n\n```{.r .cell-code}\nlm.cats.bodyClass <- lm(\n    Heart.weight ~ Sex + Body.weight.Class,\n    data = d.cats)\n\ndrop1(lm.cats.bodyClass, test = \"F\")\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\nSingle term deletions\n\nModel:\nHeart.weight ~ Sex + Body.weight.Class\n                  Df Sum of Sq    RSS    AIC F value Pr(>F)    \n<none>                         354.77 139.84                   \nSex                1      0.30 355.06 137.96  0.1166 0.7333    \nBody.weight.Class  3    350.49 705.26 232.78 45.7751 <2e-16 ***\n---\nSignif. codes:  0 '***' 0.001 '**' 0.01 '*' 0.05 '.' 0.1 ' ' 1\n```\n\n\n:::\n:::\n\n\n\n\n\n\nBody.weight.Class seems to play a relevant role, while Sex does not. This is in full agreement with the model we have seen last week where Body.weight was taken as a continuous predictor.\n\n### Question 5\n\nNow run some contrasts to see whether all pair of levels of the Body.weight.Class predictor differ from each other. Comment on the results.\n\n#### Answer\n\n\n\n\n\n\n::: {.cell}\n\n```{.r .cell-code}\nrequire(multcomp)\n```\n\n::: {.cell-output .cell-output-stderr}\n\n```\nLoading required package: multcomp\n```\n\n\n:::\n\n::: {.cell-output .cell-output-stderr}\n\n```\nLoading required package: mvtnorm\n```\n\n\n:::\n\n::: {.cell-output .cell-output-stderr}\n\n```\nLoading required package: survival\n```\n\n\n:::\n\n::: {.cell-output .cell-output-stderr}\n\n```\nLoading required package: TH.data\n```\n\n\n:::\n\n::: {.cell-output .cell-output-stderr}\n\n```\nLoading required package: MASS\n```\n\n\n:::\n\n::: {.cell-output .cell-output-stderr}\n\n```\n\nAttaching package: 'TH.data'\n```\n\n\n:::\n\n::: {.cell-output .cell-output-stderr}\n\n```\nThe following object is masked from 'package:MASS':\n\n    geyser\n```\n\n\n:::\n\n```{.r .cell-code}\nglht.1 <- glht(lm.cats.bodyClass, linfct = mcp(Body.weight.Class = \"Tukey\"))\n##\nsummary(glht.1)\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n\n\t Simultaneous Tests for General Linear Hypotheses\n\nMultiple Comparisons of Means: Tukey Contrasts\n\n\nFit: lm(formula = Heart.weight ~ Sex + Body.weight.Class, data = d.cats)\n\nLinear Hypotheses:\n                             Estimate Std. Error t value Pr(>|t|)    \n(2.3,2.7] - [2,2.3] == 0       0.7155     0.3813   1.876 0.241674    \n(2.7,3.02] - [2,2.3] == 0      2.4273     0.4382   5.539  < 1e-04 ***\n(3.02,3.9] - [2,2.3] == 0      4.6086     0.4401  10.473  < 1e-04 ***\n(2.7,3.02] - (2.3,2.7] == 0    1.7118     0.4042   4.235 0.000227 ***\n(3.02,3.9] - (2.3,2.7] == 0    3.8932     0.3816  10.202  < 1e-04 ***\n(3.02,3.9] - (2.7,3.02] == 0   2.1814     0.4166   5.236  < 1e-04 ***\n---\nSignif. codes:  0 '***' 0.001 '**' 0.01 '*' 0.05 '.' 0.1 ' ' 1\n(Adjusted p values reported -- single-step method)\n```\n\n\n:::\n:::\n\n\n\n\n\n\n### Question 6\n\nAsk generative AI to provide the interpretation of\n- the coefficients from a linear model\n- the p-values from a linear model\n\nand compare it with the definitions you find in the lecture materials. Do you think they are different in any way? Which one is easier for you to understand?\n\n#### Answer\n\nPrompt:\n\n```txt\nProvide a interpretation of the coefficients and the p-values from a linear model\n```\n> Note: Used Gemeni 3 Fast\n\nAnswer (excerpt) :\n\n```txt\nInterpreting a linear model is all about understanding the \"story\" the data is telling. When you run a regression, you’re essentially trying to find the best-fitting line through your data points[...]. The p-value tells you whether the relationship you see in the coefficient is statistically significant or if it could have just happened by random chance.[...]\n```\n\nThe general statement is accurate, although dividing p-values into “significant” and “not significant” is very bad practice.\n\n# Series 2: Non-linearities\n\n## Exercise 1\n\n\n\n\n\n\n::: {.cell}\n\n```{.r .cell-code}\n# install.packages(\"gss\")\ndata(ozone, package = \"gss\")\nhead(ozone)\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n  upo3 vdht wdsp hmdt sbtp ibht dgpg ibtp vsty day\n1    3 5710    4   28   40 2693  -25   87  250   3\n2    5 5700    3   37   45  590  -24  128  100   4\n3    5 5760    3   51   54 1450   25  139   60   5\n4    6 5720    4   69   35 1568   15  121   60   6\n5    4 5790    6   19   45 2631  -33  123  100   7\n6    4 5790    3   25   55  554  -28  182  250   8\n```\n\n\n:::\n\n```{.r .cell-code}\npairs(\n    log(upo3) ~ . ,\n    data = ozone,\n    pch = \".\",\n    upper.panel = panel.smooth\n)\n```\n\n::: {.cell-output-display}\n![](mpm1_exercises_files/figure-pdf/unnamed-chunk-14-1.pdf){fig-pos='H'}\n:::\n:::\n\n\n\n\n\n\nAs there are many predictors, the single graphs are too small. Therefore, we prefer to create each graph\nseparately. Let’s start with `vdht`.\n\n\n\n\n\n\n::: {.cell}\n\n```{.r .cell-code}\nlibrary(ggplot2)\n\nggplot(\n    data = ozone,\n    mapping = aes(\n        y = log(upo3),\n        x = vdht\n    )\n) +\ngeom_point() +\ngeom_smooth()\n```\n\n::: {.cell-output .cell-output-stderr}\n\n```\n`geom_smooth()` using method = 'loess' and formula = 'y ~ x'\n```\n\n\n:::\n\n::: {.cell-output-display}\n![](mpm1_exercises_files/figure-pdf/unnamed-chunk-15-1.pdf){fig-pos='H'}\n:::\n:::\n\n\n\n\n\n\n### Question 1\n\nGo through all the other predictors, produce the corresponding graph and comment on the relationship. You\nmay want to say whether the relationship can be assumed to be linear, quadratic or more complex. If you\nprefer, you may look at a couple of predictors only (as there are many).\n\n#### Answer\n\n\n\n\n\n\n::: {.cell}\n\n```{.r .cell-code}\nlibrary(ggplot2)\n\nggplot(\n    data = ozone,\n    mapping = aes(\n        y = log(upo3),\n        x = hmdt\n    )\n) +\ngeom_point() +\ngeom_smooth()\n```\n\n::: {.cell-output .cell-output-stderr}\n\n```\n`geom_smooth()` using method = 'loess' and formula = 'y ~ x'\n```\n\n\n:::\n\n::: {.cell-output-display}\n![](mpm1_exercises_files/figure-pdf/unnamed-chunk-16-1.pdf){fig-pos='H'}\n:::\n:::\n\n\n\n\n\n\nThe relationship between `log(upo3)` and `ibtp` appears to be linear, except at the end of the plot.\n\n\n\n\n\n\n::: {.cell}\n\n```{.r .cell-code}\nlibrary(ggplot2)\n\nggplot(\n    data = ozone,\n    mapping = aes(\n        y = log(upo3),\n        x = day\n    )\n) +\ngeom_point() +\ngeom_smooth()\n```\n\n::: {.cell-output .cell-output-stderr}\n\n```\n`geom_smooth()` using method = 'loess' and formula = 'y ~ x'\n```\n\n\n:::\n\n::: {.cell-output-display}\n![](mpm1_exercises_files/figure-pdf/unnamed-chunk-17-1.pdf){fig-pos='H'}\n:::\n:::\n\n\n\n\n\n\nThe relationship between `log(upo3)` and `day` appears to be quadratic or polynomial of order 2, 4, 6, etc.\n\n\n\n\n\n\n::: {.cell}\n\n```{.r .cell-code}\nlibrary(ggplot2)\n\nggplot(\n    data = ozone,\n    mapping = aes(\n        y = log(upo3),\n        x = sbtp\n    )\n) +\ngeom_point() +\ngeom_smooth()\n```\n\n::: {.cell-output .cell-output-stderr}\n\n```\n`geom_smooth()` using method = 'loess' and formula = 'y ~ x'\n```\n\n\n:::\n\n::: {.cell-output-display}\n![](mpm1_exercises_files/figure-pdf/unnamed-chunk-18-1.pdf){fig-pos='H'}\n:::\n:::\n\n\n\n\n\n\nThe relationship between `log(upo3)` and `sbpt` appears to be cubic or polynomial of order 3, 5, 7, etc.\n\n### Question 2\n\nFit a Generalised Additive Model with the gam() function from {mgcv} package. Remember to fit the model to the log-transformed response variable.\n\n#### Answer\n\n\n\n\n\n\n::: {.cell}\n\n```{.r .cell-code}\nlibrary(ggplot2)\nlibrary(mgcv)\n```\n\n::: {.cell-output .cell-output-stderr}\n\n```\nLoading required package: nlme\n```\n\n\n:::\n\n::: {.cell-output .cell-output-stderr}\n\n```\nThis is mgcv 1.9-4. For overview type '?mgcv'.\n```\n\n\n:::\n\n```{.r .cell-code}\ngam_ozone <- gam(\n    log(upo3) ~ s(vdht) + s(wdsp) + s(hmdt) + s(sbtp) + s(ibht) + s(dgpg) + s(ibtp) + s(vsty) + s(day),\n    data = ozone\n)\n```\n:::\n\n\n\n\n\n\n### Question 3\n\nLook at the summary of the model you just fitted and answer the following questions:\n\n\n\n\n\n\n::: {.cell}\n\n```{.r .cell-code}\nsummary(gam_ozone)\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n\nFamily: gaussian \nLink function: identity \n\nFormula:\nlog(upo3) ~ s(vdht) + s(wdsp) + s(hmdt) + s(sbtp) + s(ibht) + \n    s(dgpg) + s(ibtp) + s(vsty) + s(day)\n\nParametric coefficients:\n            Estimate Std. Error t value Pr(>|t|)    \n(Intercept)  2.21297    0.01717   128.9   <2e-16 ***\n---\nSignif. codes:  0 '***' 0.001 '**' 0.01 '*' 0.05 '.' 0.1 ' ' 1\n\nApproximate significance of smooth terms:\n          edf Ref.df      F  p-value    \ns(vdht) 1.000  1.000 10.973  0.00104 ** \ns(wdsp) 2.526  3.194  2.842  0.04113 *  \ns(hmdt) 2.353  2.958  2.546  0.04818 *  \ns(sbtp) 3.772  4.703  4.214  0.00146 ** \ns(ibht) 2.797  3.421  5.185  0.00132 ** \ns(dgpg) 3.248  4.130 14.169  < 2e-16 ***\ns(ibtp) 1.000  1.000  0.448  0.50366    \ns(vsty) 5.728  6.884  5.908 2.94e-06 ***\ns(day)  4.609  5.729 24.269  < 2e-16 ***\n---\nSignif. codes:  0 '***' 0.001 '**' 0.01 '*' 0.05 '.' 0.1 ' ' 1\n\nR-sq.(adj) =  0.826   Deviance explained = 84.1%\nGCV = 0.10629  Scale est. = 0.097256  n = 330\n```\n\n\n:::\n:::\n\n\n\n\n\n\nI) How many of the smooth terms appear to have a significant effect if we were to use a strict 5% threshold?\nII) Which smooth terms are estimated to have linear effect?\nIII) Which one is the term that is estimated to be the most complex?\nIV) Are there any “parametric” terms in this model?\n\n#### I\n\nAll smooth terms except for `ibtp` seems to have a statistical impact on the model.\n\n#### II\n\nThe two smooth terms`vdht` and `ibtp` have an estimated degree of freedom of 1. Their effect is thus estimated to be linear.\n\n#### III\n\nThe smoth term `vsty` seems to bee the most complex one.\n\n#### IV\n\nYes, there is an intercept.\n\n### Question 4\n\nUse the `plot()` function to visualise the estimated smooth terms.\n\n#### Answer\n\n\n\n\n\n\n::: {.cell}\n\n```{.r .cell-code}\nplot(\n    gam_ozone,\n    residuals = TRUE,\n    pages = 1,\n    shade = TRUE\n)\n```\n\n::: {.cell-output-display}\n![](mpm1_exercises_files/figure-pdf/unnamed-chunk-21-1.pdf){fig-pos='H'}\n:::\n:::\n\n\n\n\n\n\n# Series 3: GLMs - Binominal\n\n\n\n\n\n\n::: {.cell}\n\n```{.r .cell-code}\nd.xray <- readRDS(\"/home/nils/dev/mscids-notes/fs26/mpm1/data/Xray.RDS\")\nstr(d.xray)\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\ntibble [112 x 7] (S3: tbl_df/tbl/data.frame)\n $ Sex      : Factor w/ 2 levels \"F\",\"M\": 1 2 1 2 2 1 1 2 1 2 ...\n $ disease  : num [1:112] 1 1 0 1 1 1 1 0 0 0 ...\n $ age      : int [1:112] 0 6 8 1 4 9 17 5 0 7 ...\n $ downs    : Factor w/ 2 levels \"no\",\"yes\": 1 1 1 2 1 1 1 1 1 1 ...\n $ Mray     : Factor w/ 2 levels \"no\",\"yes\": 1 1 1 1 2 2 1 1 1 1 ...\n $ Fray     : Factor w/ 2 levels \"no\",\"yes\": 1 1 1 1 1 1 1 1 1 1 ...\n $ CnRay.num: num [1:112] 1 3 1 1 1 1 2 1 1 1 ...\n```\n\n\n:::\n:::\n\n\n\n\n\n\n## Question 1\n\nVisualise the data. You may want to take advantage of the `pairs()` function.\n\n### Answer\n\n\n\n\n\n\n::: {.cell}\n\n```{.r .cell-code}\npairs(\n    disease ~ . ,\n    data = d.xray,\n    upper.panel = panel.smooth\n)\n```\n\n::: {.cell-output-display}\n![](mpm1_exercises_files/figure-pdf/unnamed-chunk-23-1.pdf){fig-pos='H'}\n:::\n:::\n\n\n\n\n\n\n## Question 2\n\nFit a starting model to the data. Start by assuming linearity for the continuous predictors and assume that no interaction is needed. Comment on the results obtained wit the summary function.\n\n### Answer\n\n\n\n\n\n\n::: {.cell}\n\n```{.r .cell-code}\nglm.xray <- glm(\n    disease ~ Sex + downs + age + Mray + Fray + CnRay.num,\n    data = d.xray,\n    family = \"binomial\"\n)\n    \nsummary(glm.xray)\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n\nCall:\nglm(formula = disease ~ Sex + downs + age + Mray + Fray + CnRay.num, \n    family = \"binomial\", data = d.xray)\n\nCoefficients:\n              Estimate Std. Error z value Pr(>|z|)    \n(Intercept)   -2.08036    0.54863  -3.792 0.000149 ***\nSexM           0.88102    0.41952   2.100 0.035723 *  \ndownsyes      16.06989 1455.39759   0.011 0.991190    \nage            0.04494    0.04092   1.098 0.272151    \nMrayyes        0.69668    0.77274   0.902 0.367290    \nFrayyes        0.14528    0.43966   0.330 0.741064    \nCnRay.num      0.65058    0.30944   2.102 0.035514 *  \n---\nSignif. codes:  0 '***' 0.001 '**' 0.01 '*' 0.05 '.' 0.1 ' ' 1\n\n(Dispersion parameter for binomial family taken to be 1)\n\n    Null deviance: 152.97  on 111  degrees of freedom\nResidual deviance: 135.87  on 105  degrees of freedom\nAIC: 149.87\n\nNumber of Fisher Scoring iterations: 14\n```\n\n\n:::\n:::\n\n\n\n\n\n\nOnly two of total six model parameters seems to have a effect on the output (wee p-values).\n\n## Question 3\n\nInterpret the coefficients of SexM and age.\n\n### Answer\n\nWhile sex seems to have a statistical impact on the model, age does not.\n\n## Question 4\n\nLook at the estimated effect of the variable downs and its p-value. Do the results make sense to you? Comment.\n\n### Answer\n\nIt's interesting to see that only the parameters `SexM` and `CnRay.num` have a statistical impact on the model.\n\n# Series 3: GLMs - Poisson\n\n\n\n\n\n\n::: {.cell}\n\n```{.r .cell-code}\ndata(InsectSprays)\nhead(InsectSprays)\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n  count spray\n1    10     A\n2     7     A\n3    20     A\n4    14     A\n5    14     A\n6    12     A\n```\n\n\n:::\n:::\n\n\n\n\n\n\n## Question 1\n\nUse an appropriate function to visualise the data.\n\n### Answer\n\n\n\n\n\n\n::: {.cell}\n\n```{.r .cell-code}\nboxplot(count ~ spray, data = InsectSprays)\n```\n\n::: {.cell-output-display}\n![](mpm1_exercises_files/figure-pdf/unnamed-chunk-26-1.pdf){fig-pos='H'}\n:::\n:::\n\n\n\n\n\n\n## Question 2\n\nWhat do you observe on the graph? Are there differences among groups? Is the variability within each group similar?\n\n### Answer\n\nWe can clearly see that some sprays have a better effect than others.\n\n## Question 3\n\nFit a Poisson model to the data and interpret the regression coefficients.\n\n### Answer\n\n\n\n\n\n\n::: {.cell}\n\n```{.r .cell-code}\nglm.InsectSprays <- glm(\n    count ~ spray,\n    data = InsectSprays,\n    family = \"poisson\"\n)\n    \nsummary(glm.InsectSprays)\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n\nCall:\nglm(formula = count ~ spray, family = \"poisson\", data = InsectSprays)\n\nCoefficients:\n            Estimate Std. Error z value Pr(>|z|)    \n(Intercept)  2.67415    0.07581  35.274  < 2e-16 ***\nsprayB       0.05588    0.10574   0.528    0.597    \nsprayC      -1.94018    0.21389  -9.071  < 2e-16 ***\nsprayD      -1.08152    0.15065  -7.179 7.03e-13 ***\nsprayE      -1.42139    0.17192  -8.268  < 2e-16 ***\nsprayF       0.13926    0.10367   1.343    0.179    \n---\nSignif. codes:  0 '***' 0.001 '**' 0.01 '*' 0.05 '.' 0.1 ' ' 1\n\n(Dispersion parameter for poisson family taken to be 1)\n\n    Null deviance: 409.041  on 71  degrees of freedom\nResidual deviance:  98.329  on 66  degrees of freedom\nAIC: 376.59\n\nNumber of Fisher Scoring iterations: 5\n```\n\n\n:::\n:::\n\n\n\n\n\n\n## Question 4\n\nCheck whether the model is overdispersed. If this is the case, fit a quasipoisson model and compare the estimated regression coefficients with those of the Poisson model.\n\n### Answer\n\nThe residual deviance is about 98 on 66 degrees of freedom. If there were no overdispersion, we would expect the residual deviance to be about 66. We can therefore conclude that the model is overdispersed.\n\n## Question 5\n\nFormally test whether there is any evidence that the predictor spray plays a role in the “quasipoisson” model.\n\n### Answer\n\n\n\n\n\n\n::: {.cell}\n\n```{.r .cell-code}\nglm.InsectSprays <- glm(\n    count ~ spray,\n    data = InsectSprays,\n    family = \"quasipoisson\"\n)\n    \nsummary(glm.InsectSprays)\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n\nCall:\nglm(formula = count ~ spray, family = \"quasipoisson\", data = InsectSprays)\n\nCoefficients:\n            Estimate Std. Error t value Pr(>|t|)    \n(Intercept)  2.67415    0.09309  28.728  < 2e-16 ***\nsprayB       0.05588    0.12984   0.430    0.668    \nsprayC      -1.94018    0.26263  -7.388 3.30e-10 ***\nsprayD      -1.08152    0.18499  -5.847 1.70e-07 ***\nsprayE      -1.42139    0.21110  -6.733 4.82e-09 ***\nsprayF       0.13926    0.12729   1.094    0.278    \n---\nSignif. codes:  0 '***' 0.001 '**' 0.01 '*' 0.05 '.' 0.1 ' ' 1\n\n(Dispersion parameter for quasipoisson family taken to be 1.507713)\n\n    Null deviance: 409.041  on 71  degrees of freedom\nResidual deviance:  98.329  on 66  degrees of freedom\nAIC: NA\n\nNumber of Fisher Scoring iterations: 5\n```\n\n\n:::\n:::\n\n\n\n\n\n\nAs expected, there is very strong evidence that spray plays a role.\n\n## Question 6\n\nWe previously tested whether the predictor spray plays a role. Given that this test was statistically significant, we can dig further and test hypotheses that involve some of the levels of this predictor. Use the glht() function in the `multcomp` package to test whether the conventional pesticides “C”, “D” and “E” differ from the organic pesticides “A”, “B” and “F”. Test also whether the newly developed pesticides “A” and “B” differ from the old conventional pesticide “F”. Use the “quasipoisson” model to test these hypotheses.\n\n### Answer\n\n\n\n\n\n\n::: {.cell}\n\n```{.r .cell-code}\nlibrary(multcomp)\n\nglm.insects.quasi <- glm(count ~ spray - 1, data = InsectSprays, family = quasipoisson)\n\nmatrix.of.contrasts <- rbind(\n    \"organic vs conv\" = c(1/3, 1/3, -1/3, -1/3, -1/3, 1/3),\n    \"new vs old conv\" = c(1/2, 1/2, 0, 0, 0, -1)\n)\ncolnames(matrix.of.contrasts) <- levels(InsectSprays$spray)\n\nglht.insects <- glht(\n    glm.insects.quasi,\n    linfct = mcp(spray = matrix.of.contrasts)\n)\n\nsummary(glht.insects)\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n\n\t Simultaneous Tests for General Linear Hypotheses\n\nMultiple Comparisons of Means: User-defined Contrasts\n\n\nFit: glm(formula = count ~ spray - 1, family = quasipoisson, data = InsectSprays)\n\nLinear Hypotheses:\n                     Estimate Std. Error z value Pr(>|z|)    \norganic vs conv == 0   1.5461     0.1274  12.132   <1e-10 ***\nnew vs old conv == 0  -0.1113     0.1084  -1.027    0.516    \n---\nSignif. codes:  0 '***' 0.001 '**' 0.01 '*' 0.05 '.' 0.1 ' ' 1\n(Adjusted p values reported -- single-step method)\n```\n\n\n:::\n:::\n\n\n\n\n\n\nAs expected (from the graphical analysis), we can confirm that there is a clear difference between organic and conventional pesticides. However, there is no statistical evidence that the new conventional sprays differ from the old conventional one.\n\n# Series 4: Cross Validation\n\n\n\n\n\n\n::: {.cell}\n\n```{.r .cell-code}\nd.xray <- readRDS(\"/home/nils/dev/mscids-notes/fs26/mpm1/data/Xray.RDS\")\nstr(d.xray)\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\ntibble [112 x 7] (S3: tbl_df/tbl/data.frame)\n $ Sex      : Factor w/ 2 levels \"F\",\"M\": 1 2 1 2 2 1 1 2 1 2 ...\n $ disease  : num [1:112] 1 1 0 1 1 1 1 0 0 0 ...\n $ age      : int [1:112] 0 6 8 1 4 9 17 5 0 7 ...\n $ downs    : Factor w/ 2 levels \"no\",\"yes\": 1 1 1 2 1 1 1 1 1 1 ...\n $ Mray     : Factor w/ 2 levels \"no\",\"yes\": 1 1 1 1 2 2 1 1 1 1 ...\n $ Fray     : Factor w/ 2 levels \"no\",\"yes\": 1 1 1 1 1 1 1 1 1 1 ...\n $ CnRay.num: num [1:112] 1 3 1 1 1 1 2 1 1 1 ...\n```\n\n\n:::\n:::\n\n\n\n\n\n\n## Question 1\n\nFit the following four models on the whole dataset. Take a look at the summary-output of the four models. Compute the in-sample AIC-values (= AIC-values of the models fitted on the whole dataset) of all four models. You can use the function AIC(). Based on these in-sample AIC-values, which model would you select as the\nbest performing model?\n\n\n\n\n\n\n::: {.cell}\n\n```{.r .cell-code}\nlibrary(mgcv)\n\nglm.xray.simple <- glm(\n    formula = disease ~ age + Sex,\n    data = d.xray,\n    family = \"binomial\"\n)\n\nglm.xray.complex <- glm(\n    formula = disease ~ age + Sex + Mray + Fray + CnRay.num,\n    data = d.xray,\n    family = \"binomial\"\n)\n\nglm.xray.very.complex <- glm(\n    formula = disease ~ Sex * (poly(age, degree = 2) + Mray + Fray + CnRay.num),\n    data = d.xray,\n    family = \"binomial\"\n)\n\ngam.xray <- gam(\n    formula = disease ~ s(age, by = Sex) + Sex + Mray + Fray + CnRay.num,\n    data = d.xray,\n    family = \"binomial\"\n)\n```\n:::\n\n\n\n\n\n\n### Answer\n\n\n\n\n\n\n::: {.cell}\n\n```{.r .cell-code}\ncat(\"AIC of glm.xray.simple:\", AIC(glm.xray.simple),\"\\n\")\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\nAIC of glm.xray.simple: 149.63 \n```\n\n\n:::\n\n```{.r .cell-code}\ncat(\"AIC of glm.xray.complex:\", AIC(glm.xray.complex) ,\"\\n\")\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\nAIC of glm.xray.complex: 149.759 \n```\n\n\n:::\n\n```{.r .cell-code}\ncat(\"AIC of glm.xray.very.complex:\", AIC(glm.xray.very.complex),\"\\n\")\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\nAIC of glm.xray.very.complex: 158.6927 \n```\n\n\n:::\n\n```{.r .cell-code}\ncat(\"AIC of gam.xray:\", AIC(gam.xray),\"\\n\")\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\nAIC of gam.xray: 148.9194 \n```\n\n\n:::\n:::\n\n\n\n\n\n\nBased on the AIC, we should go on with the model `gam.xray` with a value of $148.9$.\n\n## Question 2\n\nCalculate the proportion of correctly classified observations in-sample (that is on the whole data set as well) for all four models. Use a cutoff of 0.5 in the predicted probability for disease. This means that if a patient has a predicted probability of 0.5 or higher, we would predict disease = 1 for this patient. Based on the in-sample proportion of correctly classified observations, which model would you choose?\n\n### Answer\n\n\n\n\n\n\n::: {.cell}\n\n```{.r .cell-code}\nprop.correct.classified <- function(model, newdata){\n    pred.probabilities <- predict(\n        object = model,\n        newdata = newdata,\n        type = \"response\"\n    )\n\n    pred.disease <- ifelse(pred.probabilities >= 0.5, 1, 0)\n    return(mean(pred.disease == newdata$disease))\n}\n```\n:::\n\n::: {.cell}\n\n```{.r .cell-code}\ncat(\"Prop. of correctly classified observations of glm.xray.simple:\", prop.correct.classified(model = glm.xray.simple, newdata = d.xray), \"\\n\")\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\nProp. of correctly classified observations of glm.xray.simple: 0.625 \n```\n\n\n:::\n\n```{.r .cell-code}\ncat(\"Prop. of correctly classified observations of glm.xray.complex:\", prop.correct.classified(model = glm.xray.complex, newdata = d.xray), \"\\n\")\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\nProp. of correctly classified observations of glm.xray.complex: 0.6785714 \n```\n\n\n:::\n\n```{.r .cell-code}\ncat(\"Prop. of correctly classified observations of glm.xray.very.complex:\", prop.correct.classified(model = glm.xray.very.complex, newdata = d.xray), \"\\n\")\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\nProp. of correctly classified observations of glm.xray.very.complex: 0.6785714 \n```\n\n\n:::\n\n```{.r .cell-code}\ncat(\"Prop. of correctly classified observations of gam.xray:\", prop.correct.classified(model = gam.xray, newdata = d.xray), \"\\n\")\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\nProp. of correctly classified observations of gam.xray: 0.75 \n```\n\n\n:::\n:::\n\n\n\n\n\n\nBased on the proportion of correctly classified observations in-sample, we should go on with the model `gam.xray` with a value of $0.75$.\n\n## Question 3\n\nNow implement 5-fold CV to compare the estimated proportion of correctly classified observations on test data. If you want, you can implement repeated 5-fold CV to see how much the estimated proportion of correctly classified observations varies between different 5-fold CVs (different permutation of the rows of the data).\n\n### Answer\n\n\n\n\n\n\n::: {.cell}\n\n```{.r .cell-code}\nset.seed(1)\n\ndf <- d.xray[sample(nrow(d.xray)), ]\n\nfolds <- cut(seq(1, nrow(df)), breaks = 5, labels = FALSE)\n\ntest_indices <- which(folds == 1)\ntest_data  <- df[test_indices, ]\ntrain_data <- df[-test_indices, ]\n```\n:::\n\n\n\n\n\n\n### Question 4\n\nBased on the results of the 5-fold CV, which of the four models would you choose and why?\n\n\n\n\n\n\n::: {.cell}\n\n```{.r .cell-code}\nlibrary(mgcv)\n\nglm.xray.simple <- glm(\n    formula = disease ~ age + Sex,\n    data = train_data,\n    family = \"binomial\"\n)\n\nglm.xray.complex <- glm(\n    formula = disease ~ age + Sex + Mray + Fray + CnRay.num,\n    data = train_data,\n    family = \"binomial\"\n)\n\nglm.xray.very.complex <- glm(\n    formula = disease ~ Sex * (poly(age, degree = 2) + Mray + Fray + CnRay.num),\n    data = train_data,\n    family = \"binomial\"\n)\n\ngam.xray <- gam(\n    formula = disease ~ s(age, by = Sex) + Sex + Mray + Fray + CnRay.num,\n    data = train_data,\n    family = \"binomial\"\n)\n```\n:::\n\n::: {.cell}\n\n```{.r .cell-code}\ncat(\"Prop. of correctly classified observations of glm.xray.simple:\", prop.correct.classified(model = glm.xray.simple, newdata = test_data), \"\\n\")\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\nProp. of correctly classified observations of glm.xray.simple: 0.6521739 \n```\n\n\n:::\n\n```{.r .cell-code}\ncat(\"Prop. of correctly classified observations of glm.xray.complex:\", prop.correct.classified(model = glm.xray.complex, newdata = test_data), \"\\n\")\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\nProp. of correctly classified observations of glm.xray.complex: 0.6086957 \n```\n\n\n:::\n\n```{.r .cell-code}\ncat(\"Prop. of correctly classified observations of glm.xray.very.complex:\", prop.correct.classified(model = glm.xray.very.complex, newdata = test_data), \"\\n\")\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\nProp. of correctly classified observations of glm.xray.very.complex: 0.5217391 \n```\n\n\n:::\n\n```{.r .cell-code}\ncat(\"Prop. of correctly classified observations of gam.xray:\", prop.correct.classified(model = gam.xray, newdata = test_data), \"\\n\")\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\nProp. of correctly classified observations of gam.xray: 0.5652174 \n```\n\n\n:::\n:::\n\n\n\n\n\n\nBased on the new proportion of correctly classified observations in-sample, we should go on with the model `glm.simple` with a value of $0.65$.",
    "supporting": [
      "mpm1_exercises_files/figure-pdf"
    ],
    "filters": [
      "rmarkdown/pagebreak.lua"
    ],
    "includes": {},
    "engineDependencies": {},
    "preserve": null,
    "postProcess": false
  }
}