{
  "hash": "757270b404ba980fcc0e2c7d680c7f82",
  "result": {
    "engine": "knitr",
    "markdown": "---\ntitle: Discrete Response, Time Series and Panel Data - Exercise 06\nauthor: Nils Rechberger\ndate: 2026-05-31\nexecute:\n  warning: false\n  message: false\n---\n\n\n\n\n# Series 6\n\n## Exercise 6.1\n\n\n\n\n::: {.cell}\n\n```{.r .cell-code}\nyields <- read.table(\"http://stat.ethz.ch/Teaching/Datasets/WBL/yields.dat\", header = FALSE)\n\nt.yields <- ts(yields[, 1])\n```\n:::\n\n\n\n\n### A\n\n\n\n\n::: {.cell}\n\n```{.r .cell-code}\nacf(t.yields)\n```\n\n::: {.cell-output-display}\n![](rtp02_exercise_06_files/figure-html/unnamed-chunk-2-1.png){width=672}\n:::\n:::\n\n::: {.cell}\n\n```{.r .cell-code}\npacf(t.yields)\n```\n\n::: {.cell-output-display}\n![](rtp02_exercise_06_files/figure-html/unnamed-chunk-3-1.png){width=672}\n:::\n:::\n\n\n\n\nThe process could be modelled by a $AR(p)$-Model with the value $p = 3$\n\n### B\n\n\n\n\n::: {.cell}\n\n```{.r .cell-code}\nr.yw <- ar(t.yields, method = \"yw\", order.max = 3)\nr.yw$resid\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\nTime Series:\nStart = 1 \nEnd = 70 \nFrequency = 1 \n [1]          NA          NA -23.2701676   8.5624227  -1.7185396   5.1017154\n [7]  10.3471780 -11.2034906   3.9364420   1.2089867  17.4563283  -9.2111662\n[13]  -2.8577303  -6.3524133   2.2572167  -2.9311234  25.3567725  14.3859910\n[19] -18.0787717  17.6571812   9.7250352   1.7201979   0.7723057   7.4553688\n[25]  -3.0885436   2.3171776   1.8505361  -7.5446312 -27.8857718   0.6164494\n[31]   6.0842678  18.0959587  11.4294237  20.8583891   5.3106389   2.4003827\n[37]  -3.7281741  -0.3234123 -13.1089096  -2.4829289   0.5084360   2.3548536\n[43]  -4.3282096   3.2157029   1.8505361   9.4553688  -3.4489132   8.6379522\n[49]  -2.7310524  -4.0412731 -11.3891299   3.5161116   8.7481019 -10.3049653\n[55]  -2.0635580   0.2900955 -18.1456261 -21.2240340   0.7913572  -2.3118589\n[61]  14.3954080  -6.6314966  -8.3591694  10.8697651  -9.0885436   2.3982863\n[67]  -6.4316031   0.8978066   6.7490614 -28.2653704\n```\n\n\n:::\n\n```{.r .cell-code}\nstr(r.yw)\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\nList of 15\n $ order       : int 2\n $ ar          : num [1:2] -0.32 0.18\n $ var.pred    : num 120\n $ x.mean      : num 51.1\n $ aic         : Named num [1:4] 9.84 0.298 0 2\n  ..- attr(*, \"names\")= chr [1:4] \"0\" \"1\" \"2\" \"3\"\n $ n.used      : int 70\n $ n.obs       : int 70\n $ order.max   : num 3\n $ partialacf  : num [1:3, 1, 1] -0.38988 0.17971 0.00226\n $ resid       : Time-Series [1:70] from 1 to 70: NA NA -23.27 8.56 -1.72 ...\n $ method      : chr \"Yule-Walker\"\n $ series      : chr \"t.yields\"\n $ frequency   : num 1\n $ call        : language ar(x = t.yields, order.max = 3, method = \"yw\")\n $ asy.var.coef: num [1:2, 1:2] 0.01444 0.00563 0.00563 0.01444\n - attr(*, \"class\")= chr \"ar\"\n```\n\n\n:::\n:::\n\n\n\n\nYule-Walker-Koeffizienten:\n\n* $\\alpha_1 = -0.32$\n* $\\alpha_2 = 0.18$\n\nModel:\n\n$$\nX_t = -0.32 \\cdot X_{t-1} + 0.18 \\cdot X_{t-2} + \\varepsilon_t\n$$\n\n### C\n\n\n\n\n::: {.cell}\n\n```{.r .cell-code}\nr.burg <- ar(t.yields, method = \"burg\", order.max = 3)\nr.burg$resid\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\nTime Series:\nStart = 1 \nEnd = 70 \nFrequency = 1 \n [1]          NA          NA -23.0964972   8.1701783  -1.3785617   4.8728473\n [7]  10.5505765 -11.1978722   3.7977236   1.3403098  17.3914298  -8.9537665\n[13]  -3.1238980  -6.2261379   2.0994588  -2.8089304  25.2454443  14.7685021\n[19] -18.1260033  17.4687299  10.0560689   1.6430522   0.8457311   7.4219430\n[25]  -2.9745155   2.2116763   1.9437802  -7.5780570 -27.9582418   0.3118307\n[31]   6.2684408  18.0559266  11.6802172  20.8533189   5.5789133   2.3108038\n[37]  -3.6390123  -0.4223073 -13.0529651  -2.6805103   0.5941087   2.3064707\n[43]  -4.2697412   3.1267173   1.9437802   9.4219430  -3.3100186   8.5134115\n[49]  -2.5474727  -4.1848533 -11.3514455   3.3500029   8.8893344 -10.2828313\n[55]  -2.2022764   0.3468193 -18.1782727 -21.4299662   0.6474050  -2.2228832\n[61]  14.3097254  -6.4014872  -8.5781282  10.8990986  -8.9745155   2.2181858\n[67]  -6.2936738   0.7334424   6.8588212 -28.2490633\n```\n\n\n:::\n\n```{.r .cell-code}\nstr(r.burg)\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\nList of 15\n $ order       : int 2\n $ ar          : num [1:2] -0.332 0.183\n $ var.pred    : num 113\n $ x.mean      : num 51.1\n $ aic         : Named num [1:4] 11.039 0.385 0 1.993\n  ..- attr(*, \"names\")= chr [1:4] \"0\" \"1\" \"2\" \"3\"\n $ n.used      : int 70\n $ n.obs       : int 70\n $ order.max   : num 3\n $ partialacf  : num [1:3, 1, 1] -0.4067 0.183 0.0103\n $ resid       : Time-Series [1:70] from 1 to 70: NA NA -23.1 8.17 -1.38 ...\n $ method      : chr \"Burg\"\n $ series      : chr \"t.yields\"\n $ frequency   : num 1\n $ call        : language ar(x = t.yields, order.max = 3, method = \"burg\")\n $ asy.var.coef: num [1:2, 1:2] 0.0136 0.0053 0.0053 0.0136\n - attr(*, \"class\")= chr \"ar\"\n```\n\n\n:::\n:::\n\n\n\n\nBurg-Koeffizienten:\n\n* $\\alpha_1 = -0.332$\n* $\\alpha_2 = 0.183$\n\nModel:\n\n$$\nX_t = -0.332 \\cdot X_{t-1} + 0.183 \\cdot X_{t-2} + \\varepsilon_t\n$$\n\n### D\n\n\n\n\n::: {.cell}\n\n```{.r .cell-code}\nr.mle <- ar(t.yields, method = \"mle\", order.max = 3)\nr.mle$resid\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\nTime Series:\nStart = 1 \nEnd = 70 \nFrequency = 1 \n [1]            NA            NA -23.083437837   7.762346509  -1.201980697\n [6]   4.561565507  10.602738000 -11.334850093   3.581349256   1.337116357\n[11]  17.216926017  -8.885802464  -3.460572312  -6.220191632   1.865930909\n[16]  -2.816243379  25.041428463  14.930022474 -18.332496024  17.218498832\n[21]  10.197216932   1.428770775   0.782162438   7.273056970  -3.008346873\n[26]   2.007435328   1.906279662  -7.726943030 -28.119035966   0.003476264\n[31]   6.334762287  17.898351229  11.739491795  20.694392418   5.637512389\n[36]   2.088058169  -3.689772086  -0.617858931 -13.115858157  -2.934860904\n[41]   0.570317679   2.153690370  -4.337204163   2.944199681   1.906279662\n[46]   9.273056970  -3.326921661   8.292016980  -2.521379225  -4.423401367\n[51] -11.422577628   3.121270050   8.899174969 -10.398085740  -2.418650744\n[56]   0.292840720 -18.318244153 -21.679521763   0.471483903  -2.242329450\n[61]  14.131552552  -6.345881671  -8.876375881  10.832761513  -9.008346873\n[66]   1.963159691  -6.288177902   0.491225167   6.843044015 -28.364092605\n```\n\n\n:::\n\n```{.r .cell-code}\nstr(r.mle)\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\nList of 15\n $ order       : int 2\n $ ar          : num [1:2] -0.341 0.187\n $ var.pred    : num 113\n $ x.mean      : num 51.2\n $ aic         : Named num [1:4] 10.808 0.301 0 1.969\n  ..- attr(*, \"names\")= chr [1:4] \"0\" \"1\" \"2\" \"3\"\n $ n.used      : int 70\n $ n.obs       : int 70\n $ order.max   : num 3\n $ partialacf  : NULL\n $ resid       : Time-Series [1:70] from 1 to 70: NA NA -23.08 7.76 -1.2 ...\n $ method      : chr \"MLE\"\n $ series      : chr \"t.yields\"\n $ frequency   : num 1\n $ call        : language ar(x = t.yields, order.max = 3, method = \"mle\")\n $ asy.var.coef: num [1:2, 1:2] 0.0136 0.0053 0.0053 0.0136\n - attr(*, \"class\")= chr \"ar\"\n```\n\n\n:::\n:::\n\n\n\n\n## Exercise 6.2\n\n\n\n\n::: {.cell}\n\n```{.r .cell-code}\nd.force <- read.table(\"http://stat.ethz.ch/Teaching/Datasets/WBL/kraft.dat\", header = FALSE)\nts.force <- ts(d.force[, 1])\n```\n:::\n\n\n\n\n### A\n\n\n\n\n::: {.cell}\n\n```{.r .cell-code}\nts.forceA <- window(ts.force, end = 280)\nplot(ts.forceA)\n```\n\n::: {.cell-output-display}\n![](rtp02_exercise_06_files/figure-html/unnamed-chunk-8-1.png){width=672}\n:::\n:::\n\n\n\n\n### B\n\n\n\n\n::: {.cell}\n\n```{.r .cell-code}\npacf(ts.forceA)\n```\n\n::: {.cell-output-display}\n![](rtp02_exercise_06_files/figure-html/unnamed-chunk-9-1.png){width=672}\n:::\n:::\n\n::: {.cell}\n\n```{.r .cell-code}\nar.force <- ar(ts.forceA, method = \"ols\", order = 6)\nar.force$aic\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n        0         1         2         3         4         5         6 \n661.05054 283.10981 180.20653 135.93284  80.06312  58.33776   0.00000 \n```\n\n\n:::\n:::\n\n\n\n\n### C\n\n\n\n\n::: {.cell}\n\n```{.r .cell-code}\nar.force <- arima(ts.forceA, order = c(6, 0, 0), method = \"ML\")\nplot(ar.force$res)\nabline(h=0, col=\"red\", lty=2)\n```\n\n::: {.cell-output-display}\n![](rtp02_exercise_06_files/figure-html/unnamed-chunk-11-1.png){width=672}\n:::\n:::\n\n\n\n\nThe model seems to be appropriate for this time series since the residuals looks normal distributed.\n",
    "supporting": [
      "rtp02_exercise_06_files"
    ],
    "filters": [
      "rmarkdown/pagebreak.lua"
    ],
    "includes": {},
    "engineDependencies": {},
    "preserve": {},
    "postProcess": true
  }
}